/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel.customerRegistration;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.cj.xdevapi.Result;
import gui.panel.AddCategories;
import gui.panel.UpdateAndRemoveCategory;
import java.awt.BorderLayout;
import model.MYSQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Customer extends javax.swing.JPanel {

    private final CustomerUpdate updateCustomer_ni;

    public Customer() {

        initComponents();
        loadCustomer();

        updateCustomer_ni = new CustomerUpdate(this);

    }

    private void loadCustomer() {

        try {

            ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `customer`");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector();
                vector.add(resultSet.getString("nic"));
                vector.add(resultSet.getString("first_name"));
                vector.add(resultSet.getString("last_name"));
                vector.add(resultSet.getString("email"));
                vector.add(resultSet.getString("no"));
                vector.add(resultSet.getString("line1"));
                vector.add(resultSet.getString("line2"));

                if (resultSet.getString("status_id").equals("1")) {
                    vector.add("Active");

                } else if (resultSet.getString("status_id").equals("2")) {
                    vector.add("Inactive");

                }
                model.addRow(vector);
            }
            jTable1.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uJTextfield5 = new component.UJTextfield();
        jLabel7 = new javax.swing.JLabel();
        uJTextfield6 = new component.UJTextfield();
        uJTextfield4 = new component.UJTextfield();
        jLabel4 = new javax.swing.JLabel();
        uJTextfield3 = new component.UJTextfield();
        jLabel2 = new javax.swing.JLabel();
        uJTextfield1 = new component.UJTextfield();
        jLabel5 = new javax.swing.JLabel();
        uJTextfield2 = new component.UJTextfield();
        uJTextfield7 = new component.UJTextfield();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Customer Registration");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nic", "First Name", "Last Name", "Email", "Address No", "Address Line 1", "Address Line 2", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(25);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel8.setText("Address Line 2");

        jLabel6.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel6.setText("Address No");

        uJTextfield5.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel7.setText("Address Line 1");

        uJTextfield6.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        uJTextfield4.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel4.setText("First Name");

        uJTextfield3.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel2.setText("NIC ");

        uJTextfield1.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel5.setText("Email");

        uJTextfield2.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        uJTextfield7.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jButton3.setText("Clear All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, java.awt.BorderLayout.LINE_END);

        jButton2.setText("Create Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uJTextfield3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(uJTextfield5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uJTextfield1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(uJTextfield7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uJTextfield4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uJTextfield6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uJTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(uJTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJTextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uJTextfield6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJTextfield7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE))
                    .addComponent(jPane1))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

//Create Account 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String nic_ni = uJTextfield1.getText();
        String email_ni = uJTextfield2.getText();
        String firstName_ni = uJTextfield3.getText();
        String larstName_ni = uJTextfield4.getText();
        String addressNo_ni = uJTextfield5.getText();
        String addressLine1_ni = uJTextfield6.getText();
        String addressLine2_ni = uJTextfield7.getText();
        String registerDate_ni = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        if (nic_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter NIC Number.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (email_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please  Enter Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (!email_ni.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (firstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter First Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (larstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Last Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (addressNo_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address No.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine1_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 1.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine2_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 2.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
//data chek
                ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `customer` WHERE `nic` = '" + nic_ni + "'OR `email` = '" + email_ni + "'");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "Customer Allredy Register ", "WARNING", JOptionPane.WARNING_MESSAGE);

                } else {
                    //data inserte
                    MYSQL.executeIUD("INSERT INTO `customer` (`nic`,`first_name`,`last_name`,`email`,`reg_date`,`avail_points`,`no`,`line1`,`line2`,`status_id`)VALUES('" + nic_ni + "','" + firstName_ni + "','" + larstName_ni + "','" + email_ni + "','" + registerDate_ni + "','0','" + addressNo_ni + "','" + addressLine1_ni + "','" + addressLine2_ni + "','" + 1 + "')");
                    JOptionPane.showMessageDialog(this, "Customer Account Create Success", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                    reset_ni();
                    loadCustomer();

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed
//creal All
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reset_ni();
    }//GEN-LAST:event_jButton3ActionPerformed
//
   


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() >= 2) {
            jPanel3.removeAll();
            jPanel3.add(updateCustomer_ni);
            SwingUtilities.updateComponentTreeUI(jPanel3);

           int row = jTable1.getSelectedRow();

            String nic_ni = String.valueOf(jTable1.getValueAt(row, 0));
            uJTextfield1.setText(nic_ni);
            uJTextfield1.setEditable(false);

            String firstName_ni = String.valueOf(jTable1.getValueAt(row, 1));
            uJTextfield3.setText(firstName_ni);

            String larstName_ni = String.valueOf(jTable1.getValueAt(row, 2));
            uJTextfield4.setText(larstName_ni);

            String email_ni = String.valueOf(jTable1.getValueAt(row, 3));
            uJTextfield2.setText(email_ni);

            String addressNo_ni = String.valueOf(jTable1.getValueAt(row, 4));
            uJTextfield5.setText(addressNo_ni);

            String addressLine1_ni = String.valueOf(jTable1.getValueAt(row, 5));
            uJTextfield6.setText(addressLine1_ni);

            String addressLine2_ni = String.valueOf(jTable1.getValueAt(row, 6));
            uJTextfield7.setText(addressLine2_ni);

        } else {
            setDefault_ni();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        setDefault_ni();

    }//GEN-LAST:event_jPanel1MouseClicked

    //default Set Create Account And Clear Button 
    private void setDefault_ni() {
        jPanel3.removeAll();
        jPanel3.add(jButton2, BorderLayout.CENTER);
        jPanel3.add(jButton3, BorderLayout.EAST);
        SwingUtilities.updateComponentTreeUI(jPanel3);
        reset_ni();
    }
//update customer
    void updateCustomer_ni() {

                   int row = jTable1.getSelectedRow();

        String nic_ni = uJTextfield1.getText();
        String email_ni = uJTextfield2.getText();
        String firstName_ni = uJTextfield3.getText();
        String larstName_ni = uJTextfield4.getText();
        String addressNo_ni = uJTextfield5.getText();
        String addressLine1_ni = uJTextfield6.getText();
        String addressLine2_ni = uJTextfield7.getText();


        if (nic_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter NIC Number.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (email_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please  Enter Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (!email_ni.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (firstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter First Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (larstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Last Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (addressNo_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address No.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine1_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 1.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine2_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 2.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
//                data chek
                ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `customer` WHERE `nic` = '" + nic_ni + "'and`first_name` = '"+firstName_ni+"'and `last_name` ='"+larstName_ni+"' and `email` = '" + email_ni + "' and `no` = '"+addressNo_ni+"'and`line1`= '"+addressLine1_ni+"'and `line2`= '"+addressLine2_ni+"' ");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "Customer details allready register", "WARNING", JOptionPane.WARNING_MESSAGE);

                } else {
                    //data inserte
                    MYSQL.executeIUD("UPDATE `customer`SET `first_name`= '" + firstName_ni + "',`last_name`= '" + larstName_ni + "',`email` = '" + email_ni + "',`no` = '" + addressNo_ni + "',`line1` = '" + addressLine1_ni + "',`line2`= '" + addressLine2_ni + "'WHERE `nic` = '" + nic_ni + "'");
                    JOptionPane.showMessageDialog(this, "Customer Account Update Success", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                    reset_ni();
                    loadCustomer();

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable jTable1;
    private component.UJTextfield uJTextfield1;
    private component.UJTextfield uJTextfield2;
    private component.UJTextfield uJTextfield3;
    private component.UJTextfield uJTextfield4;
    private component.UJTextfield uJTextfield5;
    private component.UJTextfield uJTextfield6;
    private component.UJTextfield uJTextfield7;
    // End of variables declaration//GEN-END:variables

    private void reset_ni() {
        uJTextfield1.grabFocus();
        uJTextfield1.setText("");
        uJTextfield2.setText("");
        uJTextfield3.setText("");
        uJTextfield4.setText("");
        uJTextfield5.setText("");
        uJTextfield6.setText("");
        uJTextfield7.setText("");
    }
    
     void resetcustomerUpdate_ni() {
        uJTextfield2.grabFocus();
        uJTextfield2.setText("");
        uJTextfield3.setText("");
        uJTextfield4.setText("");
        uJTextfield5.setText("");
        uJTextfield6.setText("");
        uJTextfield7.setText("");
    }
}
