/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialog;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.table.DefaultTableModel;
import model.MYSQL;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author PC
 */
public class LinkBrandCategoryDialog extends javax.swing.JDialog {

    /**
     * Creates new form LinkBrandCategoryDialog
     */
    public LinkBrandCategoryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        loadTable_vp("");
        loadBrand_vp("");
        loadCategory_vp("");
        loadProduct_vp();

        this.setLocationRelativeTo(parent);

    }

    private void loadTable_vp(String where) {
        //This method loads brand and categories 

        DefaultTableModel tm_vp = (DefaultTableModel) jTable2.getModel();
        tm_vp.setRowCount(0);

        String query_vp = "SELECT * FROM `brand` "
                + "INNER JOIN `category_has_brand` ON `brand`.`id` = `brand_id` "
                + "INNER JOIN `category` ON `category`.`id` = `category_id` " + where;
        try {
            ResultSet rsLinked_vp = MYSQL.executeSearch(query_vp);

            while (rsLinked_vp.next()) {
                Vector<String> tableVector_vp = new Vector<>();
                tableVector_vp.add(rsLinked_vp.getString("brand.name"));
                tableVector_vp.add(rsLinked_vp.getString("category.name"));

                tm_vp.addRow(tableVector_vp);

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        uJTextfield1 = new component.UJTextfield();
        uJTextfield2 = new component.UJTextfield();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/controlers/link-20.png"))); // NOI18N
        jToggleButton1.setText("Link");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jToggleButton1))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setFixedCellHeight(30);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setFixedCellHeight(30);
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel1.setText("Brand");

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setText("Category");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 153, 153));
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        uJTextfield1.setText("Search");
        uJTextfield1.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        uJTextfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uJTextfield1KeyPressed(evt);
            }
        });

        uJTextfield2.setText("Search");
        uJTextfield2.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        uJTextfield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uJTextfield2KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel3.setText("Linked Brands & Categories");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uJTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uJTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uJTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    HashMap<String, String> productMap_vp;

    private void loadProduct_vp() {
        /*There is a relationship between product and category_has_brand so if remove a row in category has brand
            some times it gives a SQLIntegrityConstraintViolationException when that has foriegned with product table.
            Here we load product to a hashmap to identify if there are a relationshp like above*/
        productMap_vp = new HashMap<>();

        try {

            ResultSet rsProduct_vp = MYSQL.executeSearch("SELECT * FROM `product` ");
            while (rsProduct_vp.next()) {
                productMap_vp.put(rsProduct_vp.getString("brand_id"), rsProduct_vp.getString("category_id"));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    HashMap<String, Integer> brandMap;

    private void loadBrand_vp(String where) {
        brandMap = new HashMap<>();
        String query = "SELECT * FROM `brand`   " + where;

        DefaultListModel<String> listModel = new DefaultListModel<>();

        listModel.setSize(0);

        try {
            //Load brand
            ResultSet rsBrand_vp = MYSQL.executeSearch(query);

            while (rsBrand_vp.next()) {

                listModel.addElement(rsBrand_vp.getString("name"));

                brandMap.put(rsBrand_vp.getString("name"), rsBrand_vp.getInt("id"));
            }

            jList1.setModel(listModel);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    HashMap<String, Integer> categoryMap;

    private void loadCategory_vp(String where) {

        categoryMap = new HashMap<>();

        String query = "SELECT * FROM `category` " + where;

        DefaultListModel<String> listModel = new DefaultListModel<>();

        listModel.setSize(0);

        try {
            //Load brand
            ResultSet rsCategory_vp = MYSQL.executeSearch(query);

            while (rsCategory_vp.next()) {

                listModel.addElement(rsCategory_vp.getString("name"));

                categoryMap.put(rsCategory_vp.getString("name"), rsCategory_vp.getInt("id"));
            }

            jList2.setModel(listModel);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void uJTextfield1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uJTextfield1KeyPressed
        if (uJTextfield1.getText().equals("Search")) {
            uJTextfield1.setText("");
        }

        String query = " WHERE `brand`.`name` LIKE '%" + uJTextfield1.getText().trim() + "%' ";
        loadTable_vp(query);

        SwingUtilities.updateComponentTreeUI(jTable2);

        loadBrand_vp(query);
    }//GEN-LAST:event_uJTextfield1KeyPressed

    private void uJTextfield2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uJTextfield2KeyPressed
        if (uJTextfield2.getText().equals("Search")) {

            uJTextfield2.setText("");
        }
        String query = " WHERE `category`.`name` LIKE '%" + uJTextfield2.getText().trim() + "%' ";
        loadTable_vp(query);

        SwingUtilities.updateComponentTreeUI(jTable2);

        loadCategory_vp(query);
    }//GEN-LAST:event_uJTextfield2KeyPressed


    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        //Brand

        selectedBrand = jList1.getSelectedValue();

        System.out.println(selectedCategory + "  " + selectedBrand);
        if (!selectedCategory.isBlank()) {

            for (int i = 0; i < jTable2.getRowCount(); i++) {

                String brand = (String) jTable2.getValueAt(i, 0);
                String category = (String) jTable2.getValueAt(i, 1);

                if (brand.equals(selectedBrand) && category.equals(selectedCategory)) {

                    //always gives one reslut because of the primary key on database is a a composite one of both brand and category
                    System.out.println("brand :" + brand + " category :" + category);

                    jToggleButton1.setSelected(true);//if there is a relationship between selected category and brand 

                    break;
                }

                jToggleButton1.setSelected(false);//if there is not a relationship between selected category and brand 
            }

        }


    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        //Category

        selectedCategory = jList2.getSelectedValue();

        System.out.println(selectedCategory + "  " + selectedBrand);

        if (!selectedBrand.isBlank()) {

            for (int i = 0; i < jTable2.getRowCount(); i++) {

                String brand = (String) jTable2.getValueAt(i, 0);
                String category = (String) jTable2.getValueAt(i, 1);

                if (brand.equals(selectedBrand) && category.equals(selectedCategory)) {

                    //always gives one reslut because of the primary key on database is a a composite one of both brand and category
                    System.out.println("brand :" + brand + " category :" + category);

                    jToggleButton1.setSelected(true);//if there is a relationship between selected category and brand 

                    break;
                }

                jToggleButton1.setSelected(false);//if there is not a relationship between selected category and brand 
            }

        }

    }//GEN-LAST:event_jList2MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
//        System.out.println(jList1.getSelectedIndex());
        if (jList1.getSelectedIndex() == -1 || jList2.getSelectedIndex() == -1) {//not selected anything
            JOptionPane.showMessageDialog(this, "Please Select a Brand and a Category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            if (jToggleButton1.isSelected()) {

                try {
                    MYSQL.executeIUD("INSERT INTO `category_has_brand` (`category_id` , `brand_id`) "
                            + " VALUES ('" + categoryMap.get(jList2.getSelectedValue()) + "'  , '" + brandMap.get(jList1.getSelectedValue()) + "'  )  ");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            } else {
                try {
                    boolean canDelete = true;
                    for (Map.Entry<String, String> entry : productMap_vp.entrySet()) {
                        String key = entry.getKey();
                        String val = entry.getValue();

                        if (key.equals(String.valueOf(brandMap.get(jList1.getSelectedValue())))) {//is there a r-ship with brand

                            if (val.equals(String.valueOf(categoryMap.get(jList2.getSelectedValue())))) {// is there a r-ship with category
                                System.out.println("1111key : " + key + " val : " + val);

                                canDelete = false;
                                break;
                            }
                            //if there is it foreigned

                            System.out.println("222key : " + key + " val : " + val);

                        }
                    }

                    if (canDelete) {
                        MYSQL.executeIUD("DELETE FROM `category_has_brand` "
                                + "WHERE `category_id` = '" + categoryMap.get(jList2.getSelectedValue()) + "' "
                                + " AND `brand_id` = '" + brandMap.get(jList1.getSelectedValue()) + "'  ");
                    } else {
                        JOptionPane.showMessageDialog(this, "Sorry this is foreigned with a product", "Can't delete", JOptionPane.WARNING_MESSAGE);
                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }

        }

        reset_vp();


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LinkBrandCategoryDialog dialog = new LinkBrandCategoryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private String selectedBrand = "";
    private String selectedCategory = "";

    private void reset_vp() {
        selectedBrand = "";
        selectedCategory = "";

        uJTextfield1.setText("Search");
        uJTextfield2.setText("Search");

        loadBrand_vp("");
        loadCategory_vp("");
        loadTable_vp("");

        jToggleButton1.setSelected(false);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private component.UJTextfield uJTextfield1;
    private component.UJTextfield uJTextfield2;
    // End of variables declaration//GEN-END:variables
}
