/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialog;

import gui.panel.order.MakeOrder;
import java.awt.Color;
import model.MYSQL;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class SelectProduct extends javax.swing.JDialog {

    /**
     * Creates new form SelectSupplier
     */
    MakeOrder makeOrderPanel;

    public SelectProduct(JPanel parent, boolean modal) {
        super((JFrame) parent.getParent().getParent().getParent().getParent().getParent().getParent().getParent().getParent(), modal);
        initComponents();
        loadProduct_vp("");
        loadUnits_vp();

        makeOrderPanel = (MakeOrder) parent;
    }

    private void loadProduct_vp(String q) {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        String query = " SELECT * FROM `product` "
                + "INNER JOIN `brand` ON `product`.`brand_id` = `brand`.`id` "
                + " INNER JOIN `category` ON `product`.`category_id` = `category`.`id` "
                + "WHERE `status` = 'Active' " + q;
        try {

            //select all the active suppliers with filters
            ResultSet resultSet = MYSQL.executeSearch(query);

            while (resultSet.next()) {
                Vector<String> vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("product.name"));
                vector.add(resultSet.getString("brand.name"));
                vector.add(resultSet.getString("category.name"));

                dtm.addRow(vector);

            }

            System.out.println(query);
            jTable1.setModel(dtm);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panalRound3 = new desingcode.PanalRound();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roundButton1 = new component.RoundButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldcategory = new javax.swing.JTextField();
        roundButton4 = new component.RoundButton();
        jFormattedTextFieldQty = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxUnit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panalRound3.setBackground(new java.awt.Color(204, 204, 204));
        panalRound3.setRoundTopLeft(40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        jLabel8.setText("Select Product");

        javax.swing.GroupLayout panalRound3Layout = new javax.swing.GroupLayout(panalRound3);
        panalRound3.setLayout(panalRound3Layout);
        panalRound3Layout.setHorizontalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(704, Short.MAX_VALUE))
        );
        panalRound3Layout.setVerticalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        roundButton1.setForeground(new java.awt.Color(102, 102, 102));
        roundButton1.setText("Clear all");
        roundButton1.setBorderColorHex("#666666");
        roundButton1.setBorderWidth("01");
        roundButton1.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jTextFieldProductName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextFieldProductName.setText("Search Product Name");
        jTextFieldProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProductNameFocusLost(evt);
            }
        });
        jTextFieldProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductNameKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldProductName);

        jTextFieldBrand.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextFieldBrand.setText("Search Brand");
        jTextFieldBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBrandFocusLost(evt);
            }
        });
        jTextFieldBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBrandKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBrandKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldBrand);

        jTextFieldcategory.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextFieldcategory.setText("Search Category");
        jTextFieldcategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldcategoryFocusLost(evt);
            }
        });
        jTextFieldcategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldcategoryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldcategoryKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldcategory);

        roundButton4.setBackground(new java.awt.Color(0, 0, 0));
        roundButton4.setForeground(new java.awt.Color(255, 255, 255));
        roundButton4.setText("Select");
        roundButton4.setBorderColorHex("#009900");
        roundButton4.setBorderWidth("0");
        roundButton4.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton4ActionPerformed(evt);
            }
        });

        jFormattedTextFieldQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00.00"))));
        jFormattedTextFieldQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldQty.setText("1");
        jFormattedTextFieldQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jFormattedTextFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldQtyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Quantity :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Brand", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jComboBoxUnit.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jComboBoxUnit.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Unit", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panalRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panalRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        clearAll_vp();
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void roundButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton4ActionPerformed
        selectProduct_vp();


    }//GEN-LAST:event_roundButton4ActionPerformed


    private void jTextFieldProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyReleased
        search_vp();
    }//GEN-LAST:event_jTextFieldProductNameKeyReleased

    private void jTextFieldBrandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBrandKeyReleased
        search_vp();
    }//GEN-LAST:event_jTextFieldBrandKeyReleased

    private void jTextFieldcategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcategoryKeyReleased
        search_vp();
    }//GEN-LAST:event_jTextFieldcategoryKeyReleased

    private void jTextFieldProductNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductNameKeyPressed
        String productName = jTextFieldProductName.getText();

        if (productName.length() >= 6 && productName.substring(0, 6).equals("Search")) {

            jTextFieldProductName.setText("");

        }
    }//GEN-LAST:event_jTextFieldProductNameKeyPressed

    private void jTextFieldBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBrandKeyPressed

        String brand = jTextFieldBrand.getText();

        if (brand.length() >= 6 && brand.substring(0, 6).equals("Search")) {

            jTextFieldBrand.setText("");
        }

    }//GEN-LAST:event_jTextFieldBrandKeyPressed

    private void jTextFieldcategoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcategoryKeyPressed

        String category = jTextFieldcategory.getText();

        if (category.length() >= 6 && category.substring(0, 6).equals("Search")) {

            jTextFieldcategory.setText("");
        }
    }//GEN-LAST:event_jTextFieldcategoryKeyPressed

    private void jTextFieldProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProductNameFocusLost
        setDefaultTextField_vp(jTextFieldProductName, "Search Product Name");
    }//GEN-LAST:event_jTextFieldProductNameFocusLost

    private void jTextFieldBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBrandFocusLost
        setDefaultTextField_vp(jTextFieldBrand, "Search Brand");
    }//GEN-LAST:event_jTextFieldBrandFocusLost

    private void jTextFieldcategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldcategoryFocusLost
        setDefaultTextField_vp(jTextFieldcategory, "Search Category");
    }//GEN-LAST:event_jTextFieldcategoryFocusLost

    private void jComboBoxUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnitActionPerformed

    private void jFormattedTextFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldQtyActionPerformed

    private void setDefaultTextField_vp(JTextField tf, String searchText) {
        if (tf.getText().isBlank()) {
            tf.setText(searchText);
        }
    }

    private void clearAll_vp() {
        jTextFieldBrand.setText("Search Brand");
        jTextFieldProductName.setText("Search Product Name");
        jTextFieldcategory.setText("Search Category");

        loadProduct_vp("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxUnit;
    private javax.swing.JFormattedTextField jFormattedTextFieldQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldcategory;
    private desingcode.PanalRound panalRound3;
    private component.RoundButton roundButton1;
    private component.RoundButton roundButton4;
    // End of variables declaration//GEN-END:variables

    private void search_vp() {
        String productName = jTextFieldProductName.getText();
        String brand = jTextFieldBrand.getText();
        String category = jTextFieldcategory.getText();

        if (productName.length() >= 6 && productName.substring(0, 6).equals("Search")) {

        } else {
            loadProduct_vp(" AND `product`.`name` LIKE '%" + productName + "%' ");
        }

        if (brand.length() >= 6 && brand.substring(0, 6).equals("Search")) {

        } else {
            loadProduct_vp(" AND `brand`.`name` LIKE '%" + brand + "%' ");
        }

        if (category.length() >= 6 && category.substring(0, 6).equals("Search")) {

        } else {
            loadProduct_vp(" AND `category`.`name` LIKE '%" + category + "%' ");
        }

    }

    private void selectProduct_vp() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
//            System.out.println("Selected row is " + jTable1.getValueAt(selectedRow, 0));

            if (jFormattedTextFieldQty.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Please enter a quantity", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (Double.valueOf(jFormattedTextFieldQty.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be grater than 0 ", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (jComboBoxUnit.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a unit for the quantity", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else {
                makeOrderPanel.setProductDetails(new String[]{
                    String.valueOf(jTable1.getValueAt(selectedRow, 0)),
                    String.valueOf(jTable1.getValueAt(selectedRow, 1)),
                    String.valueOf(jTable1.getValueAt(selectedRow, 2)),
                    String.valueOf(jTable1.getValueAt(selectedRow, 3)),
                    String.valueOf(jFormattedTextFieldQty.getText()),
                    String.valueOf(jComboBoxUnit.getSelectedItem())
                });
                this.dispose();
            }

        }

    }

    HashMap<String, String> unitMap_vp = new HashMap<>();

    private void loadUnits_vp() {

        try {
            ResultSet rs = MYSQL.executeSearch("SELECT * FROM `unit` ");
            jComboBoxUnit.removeAllItems();
            jComboBoxUnit.addItem("Select Unit");
            while (rs.next()) {

                jComboBoxUnit.addItem(rs.getString("name"));
                unitMap_vp.put(rs.getString("name"), rs.getString("id"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
