/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialog;

import gui.panel.UpdateUserEmployee;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.MYSQL;

/**
 *
 * @author Sandun
 */
public class UserEmployee extends javax.swing.JDialog {

    /**
     * Creates new form UserEmployee
     */
//    private UpdateUserEmployee updateUserEmployee_HS;
    private String USerNIC_HS;

    public UserEmployee(java.awt.Frame parent, boolean modal, String nic_HS) {
        super(parent, modal);
        initComponents();

        jButton1.putClientProperty("JButton.buttonType", "roundRect");
        uJTextfield1.setEditable(false);
        jComboBox1.setEnabled(false);
        USerNIC_HS = nic_HS;
        LoadUserEmployee(nic_HS);

//        updateUserEmployee_HS = new UpdateUserEmployee(this);
    }

    private void LoadUserEmployee(String NIC_HS) {
        try {
            uJTextfield1.setText(NIC_HS);
            ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `user` WHERE `employee_nic`='" + NIC_HS + "'");
            if (resultSet.next()) {

                jPanel1.removeAll();

                jPanel1.add(new UpdateUserEmployee(this));
                SwingUtilities.updateComponentTreeUI(jPanel1);
                jComboBox1.setEnabled(true);

                uJPasswordFiled1.setText(resultSet.getString("password"));
                jComboBox1.setSelectedItem(resultSet.getString("status"));
                jComboBox2.setSelectedItem(resultSet.getString("user_type"));

                String Reg_datetime_HS = resultSet.getString("reg_date");
                jLabel8.setText(Reg_datetime_HS);
                String Update_datetime_HS = (resultSet.getString("upd_date"));
                if (!Reg_datetime_HS.equals(Update_datetime_HS)) {
                    jLabel9.setText(Update_datetime_HS);
                } else {
                    jLabel9.setText("This Employee system not Update.");
                }

            } else {
                jLabel8.setText("This Employee system not access.");
                jLabel9.setText("This Employee system not access.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalRound1 = new desingcode.PanalRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uJTextfield1 = new component.UJTextfield();
        jLabel3 = new javax.swing.JLabel();
        uJPasswordFiled1 = new component.UJPasswordFiled();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panalRound1.setBackground(new java.awt.Color(252, 252, 252));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Employee System Access");

        jLabel2.setText("Employee NIC");

        uJTextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uJTextfield1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        jLabel4.setText("Status");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel5.setText("User Type");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Cashiers", "HR Manager", "Inventory manager" }));

        jLabel6.setText("Registered : ");

        jLabel8.setText("2025-01-15 17:52:56");

        jLabel7.setText("Updated  : ");

        jLabel9.setText("2025-01-15 17:52:56");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Close");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(9, 183, 38));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create System Access");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panalRound1Layout = new javax.swing.GroupLayout(panalRound1);
        panalRound1.setLayout(panalRound1Layout);
        panalRound1Layout.setHorizontalGroup(
            panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(uJTextfield1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uJPasswordFiled1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panalRound1Layout.createSequentialGroup()
                            .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panalRound1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panalRound1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panalRound1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(9, 9, 9))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panalRound1Layout.setVerticalGroup(
            panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(uJTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(uJPasswordFiled1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panalRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panalRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void RegUPDUserEmployee_HS(String REGUPDtype_HS) {
        String NIC_HS = uJTextfield1.getText();
        String Password_HS = String.valueOf(uJPasswordFiled1.getPassword()).trim();
        String userstatus_HS = String.valueOf(jComboBox1.getSelectedItem());
        String usertype_HS = String.valueOf(jComboBox2.getSelectedItem());
//        System.out.println(NIC_HS);
//        System.out.println(Password_HS);
//        System.out.println(userstatus_HS);
        System.out.println(usertype_HS);

        System.out.println(REGUPDtype_HS);

        if (Password_HS.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Password.", "WARNING", JOptionPane.WARNING_MESSAGE);
            uJPasswordFiled1.grabFocus();
        } else if (!Password_HS.matches("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$")) {
            JOptionPane.showMessageDialog(this, "Please enter minimum eight characters, at least one letter and one number", "Warning", JOptionPane.WARNING_MESSAGE);
            uJPasswordFiled1.grabFocus();
        } else if (usertype_HS.equals("Select Type")) {
            JOptionPane.showMessageDialog(this, "Please Select Usertype.", "WARNING", JOptionPane.WARNING_MESSAGE);
            jComboBox2.grabFocus();
        } else {
            try {
                if (REGUPDtype_HS.equals("Createaccess")) {
                    MYSQL.executeIUD("INSERT INTO `user`(`password`,`status`,`user_type`,`employee_nic`) "
                            + "VALUES ('" + Password_HS + "','" + userstatus_HS + "','" + usertype_HS + "','" + NIC_HS + "');");

                }
                if (REGUPDtype_HS.equals("Updateaccess")) {
                    MYSQL.executeIUD("UPDATE `user` SET `password`='" + Password_HS + "',`status`='" + userstatus_HS + "',"
                            + "`user_type`='" + usertype_HS + "' WHERE `employee_nic`='" + NIC_HS + "'");
                }
                this.dispose();
                
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }


    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void uJTextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uJTextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uJTextfield1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegUPDUserEmployee_HS("Createaccess");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private desingcode.PanalRound panalRound1;
    private component.UJPasswordFiled uJPasswordFiled1;
    private component.UJTextfield uJTextfield1;
    // End of variables declaration//GEN-END:variables
}
