/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel;

import javax.swing.JOptionPane;
import model.MYSQL;

/**
 *
 * @author PC
 */
public class AddCategories extends javax.swing.JPanel {

    private final Categories categories_vp;

    /**
     * Creates new form AddCategories
     * @param c
     */
    public AddCategories(Categories c) {
        initComponents();
        this.categories_vp = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJTextfield1 = new component.UJTextfield();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        uJTextfield1.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(uJTextfield1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uJTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String category_vp = uJTextfield1.getText().trim();
        if (category_vp.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter a category", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                if (MYSQL.executeSearch("SELECT * FROM `category` WHERE `name` = '"+category_vp+"'").next()) {
                    JOptionPane.showMessageDialog(this, "The category is already existed.", "Warning", JOptionPane.WARNING_MESSAGE);
                }else{
                    MYSQL.executeIUD("INSERT INTO `category` (`name`) VALUES ('" + category_vp + "')");
                    categories_vp.loadCategories_vp();
                    uJTextfield1.setText("");

                }
                uJTextfield1.grabFocus();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private component.UJTextfield uJTextfield1;
    // End of variables declaration//GEN-END:variables
}
