/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel;

import java.awt.Color;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.MYSQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import model.jasper.Report;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Sandun
 */
public class attendance extends javax.swing.JPanel {

    /**
     * Creates new form attendance
     */
    private ResultSet atresultSet_HS;
    private final SimpleDateFormat Dateformat;
    private Date date;
    private final Color Markcolor;
    private String ASC_DESC;

    public attendance() {
        initComponents();
        Markcolor = new Color(51, 204, 0);
        Dateformat = new SimpleDateFormat("yyyy-MM-dd");
        date = new Date();
        ASC_DESC = "";
        attendanceLoad("WHERE `attendance`.`date`='" + Dateformat.format(date) + "'");
    }

    private void attendanceLoad(String query) {
        try {
            AttendenceSearch(query);
            DefaultTableModel attTablemodel_HS = (DefaultTableModel) attendancejTable1.getModel();
            attTablemodel_HS.setRowCount(0);
            while (atresultSet_HS.next()) {
                Vector v = new Vector<>();
                v.add(atresultSet_HS.getString("nic"));
                v.add(atresultSet_HS.getString("fname") + " " + atresultSet_HS.getString("lname"));
                boolean isNewEmployee = false;
                if (atresultSet_HS.getString("time") == null) {
                    v.add("New Employee");
                    isNewEmployee = true;
                } else {
                    v.add(atresultSet_HS.getString("time"));
                }

                if ( (atresultSet_HS.getString("time") != null && atresultSet_HS.getString("leaving") == null) ||  isNewEmployee) {
                    v.add("Not Mark");                
                } else {
                    v.add(atresultSet_HS.getString("leaving"));
                }

                attTablemodel_HS.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void AttendenceSearch(String query) throws Exception {
        atresultSet_HS = MYSQL.executeSearch("SELECT * FROM `employee` LEFT JOIN `attendance` ON `employee`.`nic`=`attendance`.`employee_nic` " + query + ASC_DESC);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        attenjTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        attenjButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendancejTable1 = new javax.swing.JTable();
        attenjComboBox1 = new javax.swing.JComboBox<>();
        roundButton1 = new component.RoundButton();
        panalRound3 = new desingcode.PanalRound();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(360, 360));

        attenjTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                attenjTextField1KeyReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/profile-user.gif"))); // NOI18N

        jPanel3.setLayout(new java.awt.BorderLayout());

        attenjButton1.setBackground(new java.awt.Color(51, 204, 0));
        attenjButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        attenjButton1.setForeground(new java.awt.Color(255, 255, 255));
        attenjButton1.setText("Mark");
        attenjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attenjButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(attenjButton1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attenjTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(attenjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        attendancejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Name", "Come", "Leave"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attendancejTable1.setRowHeight(30);
        attendancejTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancejTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(attendancejTable1);

        attenjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date DESC", "Date ASC" }));
        attenjComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                attenjComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        roundButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/print-26.png"))); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });

        panalRound3.setBackground(new java.awt.Color(244, 244, 244));
        panalRound3.setRoundTopLeft(40);

        jLabel8.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Attendance");

        javax.swing.GroupLayout panalRound3Layout = new javax.swing.GroupLayout(panalRound3);
        panalRound3.setLayout(panalRound3Layout);
        panalRound3Layout.setHorizontalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panalRound3Layout.setVerticalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panalRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(attenjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panalRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attenjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void attenjTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attenjTextField1KeyReleased
        // TODO add your handling code here:
        String NIC_HS = attenjTextField1.getText();
        attendanceLoad("WHERE `nic` LIKE '%" + NIC_HS + "%'");
        if (NIC_HS.matches("^[0-9]{9}[Vv]$") || NIC_HS.matches("^[0-9]{12}$")) {
            checkMark();
        } else {
            attenjButton1.setText("Mark");
            attenjButton1.setBackground(Markcolor);
        }
    }//GEN-LAST:event_attenjTextField1KeyReleased

    private void attenjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attenjButton1ActionPerformed
        // TODO add your handling code here:
        String NIC_HS = attenjTextField1.getText();
        try {
            if (NIC_HS.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter NIC.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (!NIC_HS.matches("^[0-9]{9}[Vv]$") & !NIC_HS.matches("^[0-9]{12}$")) {
                JOptionPane.showMessageDialog(this, "Invalid NIC.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                ResultSet res_atEmp_HS = MYSQL.executeSearch("SELECT * FROM `employee` LEFT JOIN `attendance` ON `employee`.`nic`=`attendance`.`employee_nic` WHERE `nic`='" + attenjTextField1.getText() + "' ORDER BY `time` DESC");

                if (res_atEmp_HS.next()) {
                    if (res_atEmp_HS.getString("nic").equals(NIC_HS) && res_atEmp_HS.getString("date") == null) {
                        ComeAttendance(NIC_HS, Dateformat.format(date));
                        clean();
                    } else if (res_atEmp_HS.getString("nic").equals(NIC_HS) && res_atEmp_HS.getString("date").equals(Dateformat.format(date)) && res_atEmp_HS.getString("leaving") != null) {
                        JOptionPane.showMessageDialog(this, "Today you have already mark form exit", "Information", JOptionPane.INFORMATION_MESSAGE);
                        //ComeAttendance(NIC_HS);
                        clean();

                    } else if (res_atEmp_HS.getString("nic").equals(NIC_HS) && res_atEmp_HS.getString("date").equals(Dateformat.format(date)) && res_atEmp_HS.getString("leaving") == null) {
                        SimpleDateFormat smptime = new SimpleDateFormat("HH:mm:ss");
                        leaving(NIC_HS, smptime.format(date), Dateformat.format(date));
                        clean();
                    } else {
                        ComeAttendance(NIC_HS, Dateformat.format(date));
                        clean();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "This NIC does not have a Employe.", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_attenjButton1ActionPerformed

    private void attendancejTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancejTable1MouseClicked
        // TODO add your handling code here:
        int Selectedrow_HS = attendancejTable1.getSelectedRow();
        String NIC_HS = String.valueOf(attendancejTable1.getValueAt(Selectedrow_HS, 0));
        attenjTextField1.setText(NIC_HS);
        checkMark();
        attendanceLoad("WHERE `nic` LIKE '%" + attenjTextField1.getText() + "%'");

    }//GEN-LAST:event_attendancejTable1MouseClicked

    private void attenjComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_attenjComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String Orderpattern_HS = String.valueOf(attenjComboBox1.getSelectedItem());
        if (Orderpattern_HS == "Date ASC") {
            ASC_DESC = " ORDER BY `time` ASC";
        } else if (Orderpattern_HS == "Date DESC") {
            ASC_DESC = " ORDER BY `time` DESC";
        }
        attendanceLoad("WHERE `nic` LIKE '%" + attenjTextField1.getText() + "%'  ");
    }//GEN-LAST:event_attenjComboBox1PopupMenuWillBecomeInvisible

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        try {

            HashMap<String, Object> map = new HashMap<>();
            JRTableModelDataSource dataSource = new JRTableModelDataSource(attendancejTable1.getModel());
            JasperPrint print = JasperFillManager.fillReport("src/reports/attendance/AttendanceReport.jasper", map, dataSource);
            Report.execute(print);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_roundButton1ActionPerformed

    private void checkMark() {
        try {
            ResultSet res_atEmp_HS = MYSQL.executeSearch("SELECT * FROM  `attendance`  WHERE `employee_nic`='" + attenjTextField1.getText() + "' AND `date`='" + Dateformat.format(date) + "'");
            if (res_atEmp_HS.next()) {
                if (res_atEmp_HS.getString("leaving") != null) {
                    attenjButton1.setText("You Marked");
                    attenjButton1.setBackground(Color.BLUE);
                } else {
                    attenjButton1.setText("Leaving");
                    attenjButton1.setBackground(Color.red);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void ComeAttendance(String nic, String ToDay) throws Exception {
        MYSQL.executeIUD("INSERT INTO `attendance` (`employee_nic`,`date`) VALUES ('" + nic + "','" + ToDay + "')");
    }

    public static void leaving(String nic, String leaving, String ToDay) throws Exception {
        MYSQL.executeIUD("UPDATE `attendance` SET `leaving`='" + leaving + "' WHERE `date`='" + ToDay + "' AND `employee_nic`='" + nic + "'");
    }

    private void clean() {
        attendanceLoad("WHERE `attendance`.`date`='" + Dateformat.format(date) + "'");
        attenjTextField1.setText("");
        attenjButton1.setText("Mark");
        attenjButton1.setBackground(Markcolor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendancejTable1;
    private javax.swing.JButton attenjButton1;
    private javax.swing.JComboBox<String> attenjComboBox1;
    private javax.swing.JTextField attenjTextField1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private desingcode.PanalRound panalRound3;
    private component.RoundButton roundButton1;
    // End of variables declaration//GEN-END:variables
}
