/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel;

import java.awt.Panel;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.MYSQL;

/**
 *
 * @author lgpavithra
 *
 */
public class Brand extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final AddBrand addBrand_vp;
    private final UpdateAndRemoveBrand updateAndRemoveBrand_vp;

    public Brand() {
        initComponents();

        addBrand_vp = new AddBrand(this);
        updateAndRemoveBrand_vp = new UpdateAndRemoveBrand(this);
        jPanel1.add(addBrand_vp);
        loadBrand_vp("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Brands");

        jLabel2.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel2.setText("Name ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(130);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(160);
        }

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 428, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        updateAndRemoveBrand_vp.jButton1.setEnabled(true);
        if (evt.getClickCount() >= 2) {
            jPanel1.removeAll();
            jPanel1.add(updateAndRemoveBrand_vp);
            updateAndRemoveBrand_vp.currentBrand_vp = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
            updateAndRemoveBrand_vp.uJTextfield1.setText(updateAndRemoveBrand_vp.currentBrand_vp);
            SwingUtilities.updateComponentTreeUI(jPanel1);
            
            try {
                if (MYSQL.executeSearch("SELECT * FROM `category_has_brand` INNER JOIN `brand`"
                        + "  ON `category_has_brand`.`brand_id` = `brand`.`id` WHERE `brand`.`name` = '"+String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1))+"'").next()) {

                    updateAndRemoveBrand_vp.jButton1.setEnabled(false);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            reset_vp();
            

        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        reset_vp();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    void loadBrand_vp(String q) {
        try {
            ResultSet rs_vp = MYSQL.executeSearch("SELECT * FROM `brand`" +q);
            DefaultTableModel dtm_vp = (DefaultTableModel) jTable1.getModel();
            dtm_vp.setRowCount(0);
            while (rs_vp.next()) {
                Vector v = new Vector<String>();
                v.add(rs_vp.getString("id"));
                v.add(rs_vp.getString("name"));
                dtm_vp.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void reset_vp(){
        jPanel1.removeAll();
        jPanel1.add(addBrand_vp);
        SwingUtilities.updateComponentTreeUI(this);
        this.grabFocus();
    }

}
