/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import gui.panel.attendance;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;
import model.MYSQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Sandun
 */
public class Log_in extends javax.swing.JFrame {

    /**
     * @return the username
     */
    private static String username; //Sandun
    public static Frame Dashboaed_Fram_HS;

    public static String getUsername() {
        return username;
    }

    /**
     * @param Username the username to set
     */
    public static void setUsername(String Username) {
        username = Username;
    }

    /**
     * Creates new form Log_in
     */
    public Log_in() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        OtherinitComponents();
    }

    private void OtherinitComponents() {

        jButton2.setBackground(new Color(0, 0, 0, 0));
        jButton2.setBorder(null);
        jTextField1.putClientProperty("JComponent.roundRect", true);
        jTextField1.putClientProperty(FlatClientProperties.STYLE, "margin:0,16,0,10");
        jPasswordField1.putClientProperty("JComponent.roundRect", true);
        jPasswordField1.putClientProperty(FlatClientProperties.STYLE, "margin:0,16,0,10");
        jButton1.putClientProperty("JButton.buttonType", "roundRect");
        jTextField1.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalRound1 = new desingcode.PanalRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panalRound2 = new desingcode.PanalRound();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        panalRound3 = new desingcode.PanalRound();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panalRound1.setBackground(new java.awt.Color(144, 163, 175));
        panalRound1.setRoundBottomLeft(40);
        panalRound1.setRoundBottomRight(40);
        panalRound1.setRoundTopLeft(40);
        panalRound1.setRoundTopRight(40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 74)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("to");

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FeelFresh");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Software was created by team Legacy");

        panalRound2.setBackground(new java.awt.Color(204, 204, 204));
        panalRound2.setRoundBottomRight(130);
        panalRound2.setRoundTopLeft(130);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(237, 235, 235));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panalRound2Layout = new javax.swing.GroupLayout(panalRound2);
        panalRound2.setLayout(panalRound2Layout);
        panalRound2Layout.setHorizontalGroup(
            panalRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panalRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panalRound2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panalRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panalRound2Layout.setVerticalGroup(
            panalRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        panalRound3.setBackground(new java.awt.Color(108, 140, 161));
        panalRound3.setRoundBottomLeft(40);
        panalRound3.setRoundTopRight(40);

        jButton2.setBackground(new java.awt.Color(108, 140, 161));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-close-20.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/icons8-rclose-20.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panalRound3Layout = new javax.swing.GroupLayout(panalRound3);
        panalRound3.setLayout(panalRound3Layout);
        panalRound3Layout.setHorizontalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panalRound3Layout.setVerticalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panalRound1Layout = new javax.swing.GroupLayout(panalRound1);
        panalRound1.setLayout(panalRound1Layout);
        panalRound1Layout.setHorizontalGroup(
            panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panalRound1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound1Layout.createSequentialGroup()
                        .addComponent(panalRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addComponent(panalRound3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panalRound1Layout.setVerticalGroup(
            panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound1Layout.createSequentialGroup()
                .addGroup(panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panalRound1Layout.createSequentialGroup()
                        .addComponent(panalRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(panalRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panalRound1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panalRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panalRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Log_in_Action() {

        try {

            String Username = jTextField1.getText().trim();
            String password = String.valueOf(jPasswordField1.getPassword()).trim();

            if (Username.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter your username", "Warning", JOptionPane.WARNING_MESSAGE);
                jTextField1.grabFocus();
            } else if (password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter your password.", "Warning", JOptionPane.WARNING_MESSAGE);
                jPasswordField1.grabFocus();

            } else {
                ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `user` WHERE `employee_nic`='" + Username + "' AND `password`='" + password + "'");

                if (resultSet.next()) {

                    if (resultSet.getString("status").equals("Active")) {//checking that either acvive or inactive

                        if (resultSet.getString("user_type").equals("Inventory manager")) {//checking that the user type is invenotory manager.
                            Dashboaed_Fram_HS = new Dashboard_inventoryManager(Username);
                            Dashboaed_Fram_HS.setVisible(true);
                        }
                        if (resultSet.getString("user_type").equals("Cashiers")) {
                            Dashboaed_Fram_HS = new Dashboard_cashier(Username);
                            Dashboaed_Fram_HS.setVisible(true);
                        }
                        if (resultSet.getString("user_type").equals("HR Manager")) {
                            Dashboaed_Fram_HS = new Dashboard_hR_Manager();
                            Dashboaed_Fram_HS.setVisible(true);
                        }
                        if (resultSet.getString("user_type").equals("Admin")) {
                            new Main_Dashbord().setVisible(true);
                        }
                        ResultSet res_atEmp_HS = MYSQL.executeSearch("SELECT * FROM `employee` LEFT JOIN `attendance` ON `employee`.`nic`=`attendance`.`employee_nic` WHERE `nic`='" + Username + "' ORDER BY `time` DESC");
                        if (res_atEmp_HS.next()) {
                            SimpleDateFormat Dateformat = new SimpleDateFormat("yyyy-MM-dd");
                            Date date = new Date();
                            if (res_atEmp_HS.getString("nic").equals(Username) && !res_atEmp_HS.getString("date").equals(Dateformat.format(date))) {
                                attendance.ComeAttendance(Username, Dateformat.format(date));
                            }
                        }
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Your user status is " + resultSet.getString("status"), "Warning ", JOptionPane.WARNING_MESSAGE);
                    }
                    setUsername(Username);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Username or Passwors", "Warning", JOptionPane.WARNING_MESSAGE);
                    jTextField1.grabFocus();

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Log_in_Action();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == 10) {
            Log_in_Action();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == 10) {
            Log_in_Action();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == 10) {
            Log_in_Action();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private desingcode.PanalRound panalRound1;
    private desingcode.PanalRound panalRound2;
    private desingcode.PanalRound panalRound3;
    // End of variables declaration//GEN-END:variables
}
