/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel.order;

import gui.Dashboard_inventoryManager;
import gui.dialog.SelectProduct;
import gui.dialog.SelectSupplier_order;
import java.awt.Color;

import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.MYSQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.HashMap;
import model.Email;
import raven.toast.Notifications;
import raven.toast.ToastClientProperties;

/**
 *
 * @author lgpavithra
 */
public class MakeOrder extends javax.swing.JPanel {

    private String supplierId_vp;
    private String[] productDetails_vp;
    DefaultTableModel tableModelFull_vp;//table model without filters

    public Dashboard_inventoryManager parentFrame_vp;

    /**
     * @param productDetails the productDetails_vp to set
     */
    public void setProductDetails(String[] productDetails) {

        // [0] id, [1] product name, [2] brand, [3] category, [4] qty , [5] unit
        clearFilter_vp();

        this.productDetails_vp = productDetails;

        if (jTable1.getRowCount() > 0) {
            Boolean foundColumn = false;
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                if (jTable1.getValueAt(i, 0).equals(productDetails[0])) {//if a row is avaliable

                    foundColumn = true;
                    //update quantity  

                    int option = JOptionPane.showConfirmDialog(this, "This item already exists. "
                            + "Do you want to update the quantity (This will add this quantity to existing quantity)", "Information", JOptionPane.INFORMATION_MESSAGE);

                    if (option == 0) {
                        jTable1.setValueAt(String.valueOf(Double.valueOf(productDetails[4]) + Double.valueOf((String) jTable1.getValueAt(i, 4))), i, 4);
                    }

                }
            }

            if (!foundColumn) {//it is no any row to match
                //set to table 
                Vector<String> vector = new Vector();
                vector.add(productDetails[0]);
                vector.add(productDetails[1]);
                vector.add(productDetails[2]);
                vector.add(productDetails[3]);
                vector.add(productDetails[4]);
                vector.add(productDetails[5]);

                DefaultTableModel dtm = tableModelFull_vp;
                dtm.addRow(vector);
            }

        } else {//row count is zero
            //set to table 
            Vector<String> vector = new Vector();
            vector.add(productDetails[0]);
            vector.add(productDetails[1]);
            vector.add(productDetails[2]);
            vector.add(productDetails[3]);
            vector.add(productDetails[4]);
            vector.add(productDetails[5]);

            DefaultTableModel dtm = tableModelFull_vp;
            dtm.addRow(vector);
        }

        SwingUtilities.updateComponentTreeUI(this);

    }

    /**
     * Creates new form NewJPanel
     */
    public MakeOrder(JFrame parentFrame) {
        this.parentFrame_vp = (Dashboard_inventoryManager) parentFrame;
        initComponents();
        tableModelFull_vp = (DefaultTableModel) jTable1.getModel();

        loadCategories_vp();
        loadBrand();
        loadUnits_vp();

        Notifications.getInstance().setJFrame(this.parentFrame_vp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePendingOrder = new javax.swing.JScrollPane();
        jListPendingOrder = new javax.swing.JList<>();
        IdLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jComboBoxBrand = new javax.swing.JComboBox<>();
        jTextFieldSearchProduct = new javax.swing.JTextField();
        roundButton1 = new component.RoundButton();
        panalRound3 = new desingcode.PanalRound();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        roundButton6 = new component.RoundButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldQty = new javax.swing.JFormattedTextField();
        jComboBoxUnit = new javax.swing.JComboBox<>();
        roundButtonUpdateQTY = new component.RoundButton();
        roundButton5 = new component.RoundButton();
        roundButton3 = new component.RoundButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panalRound4 = new desingcode.PanalRound();
        jLabel5 = new javax.swing.JLabel();
        panalRound1 = new desingcode.PanalRound();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanelNoPendingOrders = new javax.swing.JPanel();
        jLabelNoPending = new javax.swing.JLabel();
        jLabelOrders = new javax.swing.JLabel();
        jLabelAvaliable = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        jScrollPanePendingOrder.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePendingOrder.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jListPendingOrder.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jListPendingOrder.setForeground(new java.awt.Color(51, 51, 51));
        jListPendingOrder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPendingOrder.setFixedCellHeight(30);
        jScrollPanePendingOrder.setViewportView(jListPendingOrder);

        IdLabel.setText("ID");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxCategory.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jComboBoxCategory.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Category", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jComboBoxBrand.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jComboBoxBrand.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Brand", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBrandActionPerformed(evt);
            }
        });

        jTextFieldSearchProduct.setText("Search added products");
        jTextFieldSearchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchProductKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchProductKeyReleased(evt);
            }
        });

        roundButton1.setForeground(new java.awt.Color(102, 102, 102));
        roundButton1.setText("Clear Filters");
        roundButton1.setArc(15);
        roundButton1.setBorderColorHex("#666666");
        roundButton1.setBorderWidth("01");
        roundButton1.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSearchProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panalRound3.setBackground(new java.awt.Color(244, 244, 244));
        panalRound3.setRoundTopLeft(40);
        panalRound3.setRoundTopRight(40);

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 71, 23));
        jLabel8.setText("Message Body");

        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout panalRound3Layout = new javax.swing.GroupLayout(panalRound3);
        panalRound3.setLayout(panalRound3Layout);
        panalRound3Layout.setHorizontalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        panalRound3Layout.setVerticalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addGap(6, 6, 6))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Required Date");

        roundButton6.setBackground(new java.awt.Color(51, 102, 255));
        roundButton6.setForeground(new java.awt.Color(255, 255, 255));
        roundButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/dashboard/inventory/place order/icons8-send-48.png"))); // NOI18N
        roundButton6.setText("Place Order");
        roundButton6.setBorderColorHex("#009900");
        roundButton6.setBorderWidth("0");
        roundButton6.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Quantity");

        jFormattedTextFieldQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00.00"))));
        jFormattedTextFieldQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jFormattedTextFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldQtyKeyPressed(evt);
            }
        });

        jComboBoxUnit.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jComboBoxUnit.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Unit" }));
        jComboBoxUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnitActionPerformed(evt);
            }
        });

        roundButtonUpdateQTY.setBackground(new java.awt.Color(51, 102, 255));
        roundButtonUpdateQTY.setForeground(new java.awt.Color(255, 255, 255));
        roundButtonUpdateQTY.setText("Update Qty");
        roundButtonUpdateQTY.setArc(15);
        roundButtonUpdateQTY.setAutoscrolls(true);
        roundButtonUpdateQTY.setBorderColorHex("#009900");
        roundButtonUpdateQTY.setBorderWidth("0");
        roundButtonUpdateQTY.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButtonUpdateQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButtonUpdateQTYActionPerformed(evt);
            }
        });

        roundButton5.setForeground(new java.awt.Color(51, 51, 51));
        roundButton5.setText("Add");
        roundButton5.setArc(15);
        roundButton5.setAutoscrolls(true);
        roundButton5.setBorderColorHex("#aaaaaa");
        roundButton5.setFont(new java.awt.Font("Quicksand SemiBold", 0, 16)); // NOI18N
        roundButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton5ActionPerformed(evt);
            }
        });

        roundButton3.setBackground(new java.awt.Color(255, 51, 51));
        roundButton3.setForeground(new java.awt.Color(255, 255, 255));
        roundButton3.setText("Remove");
        roundButton3.setArc(15);
        roundButton3.setBorderColorHex("#E70101");
        roundButton3.setBorderWidth("0");
        roundButton3.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxUnit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundButtonUpdateQTY, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(roundButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(roundButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundButtonUpdateQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roundButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roundButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Category", "Brand", "QTY", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        panalRound4.setBackground(new java.awt.Color(244, 244, 244));
        panalRound4.setRoundTopLeft(50);

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Make Order");

        javax.swing.GroupLayout panalRound4Layout = new javax.swing.GroupLayout(panalRound4);
        panalRound4.setLayout(panalRound4Layout);
        panalRound4Layout.setHorizontalGroup(
            panalRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panalRound4Layout.setVerticalGroup(
            panalRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        panalRound1.setBackground(new java.awt.Color(244, 244, 244));
        panalRound1.setRoundBottomLeft(30);
        panalRound1.setRoundBottomRight(30);
        panalRound1.setRoundTopLeft(30);
        panalRound1.setRoundTopRight(30);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));

        nameLabel.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        nameLabel.setText("Name :");

        emailLabel.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        emailLabel.setText("e-Mail :");

        mobileLabel.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        mobileLabel.setText("Mobile :");

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanelNoPendingOrders.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNoPendingOrders.setLayout(new java.awt.GridLayout(3, 0));

        jLabelNoPending.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabelNoPending.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNoPending.setText("  No Pending");
        jPanelNoPendingOrders.add(jLabelNoPending);

        jLabelOrders.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabelOrders.setForeground(new java.awt.Color(102, 102, 102));
        jLabelOrders.setText("  Orders");
        jPanelNoPendingOrders.add(jLabelOrders);

        jLabelAvaliable.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabelAvaliable.setForeground(new java.awt.Color(102, 102, 102));
        jLabelAvaliable.setText("  Avaliable");
        jPanelNoPendingOrders.add(jLabelAvaliable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNoPendingOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jPanelNoPendingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Select a Supplier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mobileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout panalRound1Layout = new javax.swing.GroupLayout(panalRound1);
        panalRound1.setLayout(panalRound1Layout);
        panalRound1Layout.setHorizontalGroup(
            panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panalRound1Layout.setVerticalGroup(
            panalRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panalRound4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panalRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panalRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panalRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panalRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panalRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBrandActionPerformed

        addFilterSearch();

    }//GEN-LAST:event_jComboBoxBrandActionPerformed

    private void roundButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton5ActionPerformed

        SelectProduct selectProduct = new SelectProduct(this, true);
        selectProduct.setLocationRelativeTo(this);
        selectProduct.setVisible(true);

    }//GEN-LAST:event_roundButton5ActionPerformed

    private void roundButtonUpdateQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButtonUpdateQTYActionPerformed
        int row = jTable1.getSelectedRow();
        if (JOptionPane.showConfirmDialog(this, "Do you want to update qty of " + jTable1.getValueAt(row, 1) + "", "Information", JOptionPane.INFORMATION_MESSAGE) == 0) {
            jTable1.setValueAt(jFormattedTextFieldQty.getText(), row, 4);
        }


    }//GEN-LAST:event_roundButtonUpdateQTYActionPerformed

    int status = 3; //this is shows whether email is sent or not /0-sent , 1-failed , 3-wait for resilt

    private void roundButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton6ActionPerformed

        if (IdLabel.getText().equals("ID")) {//it was not selected a supplier
            JOptionPane.showMessageDialog(this, "Please select a supplier", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jTable1.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "There are no product has added", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a required date ", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jTextArea1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Message Body is empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // every fields are filled
            String supplierId = null;

            try {//retrieving supplier id
                ResultSet rsSupplier = MYSQL.executeSearch("SELECT * FROM `supplier` WHERE `id` = '" + IdLabel.getText() + "' ");
                if (rsSupplier.next()) {
                    supplierId = rsSupplier.getString("id");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            if (supplierId != null) {
                try {

                    //This preparedStatement is used for retrieving the primary key of currently inserted row
                    PreparedStatement preStatement = MYSQL.connection.prepareStatement("INSERT INTO `order` (`supplier_id`,`status`,`required_date`,`message`,`user_employee_nic`)"
                            + " VALUES ('" + supplierId + "','Pending',"//default set as pending
                            + " '" + new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate()) + "',"
                            + " '" + jTextArea1.getText() + "',"
                            + "  '200388895632' )  ", Statement.RETURN_GENERATED_KEYS);//Here User id has inserted manually **********************
                    //Toast message is better for this -T

                    preStatement.executeUpdate();
                    ResultSet rsKeys = preStatement.getGeneratedKeys();//retrieving the primary key

                    if (rsKeys.next()) {

                        long order_id = rsKeys.getLong(1);

                        String q = "";//columns to insert
                        for (int i = 0; i < tableModelFull_vp.getRowCount(); i++) {
                            String product_id = String.valueOf(tableModelFull_vp.getValueAt(i, 0));
                            String qty = String.valueOf(tableModelFull_vp.getValueAt(i, 4));
                            String unit = unitMap_vp.get(tableModelFull_vp.getValueAt(i, 5));

                            if (q.isBlank()) {
                                q = "('" + order_id + "' , '" + product_id + "' , '" + qty + "' , '" + unit + "')";
                            } else {
                                q += ", ('" + order_id + "' , '" + product_id + "' , '" + qty + "' , '" + unit + "')";
                            }
                        }

                        try {

                            MYSQL.executeIUD("INSERT INTO `order_item` (`order_id`,`product_id`,`qty`,`unit_id`) VALUES "
                                    + q + " ");

                            Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Order Saved");
                            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER, "Please wait until send the email!");

                            Thread tStatus = new Thread(() -> {
                                while (status == 3) {
                                    String text = this.parentFrame_vp.jLabelProgress.getText();
                                    this.parentFrame_vp.jLabelProgress.setText(text + "|||");
                                    try {
                                        Thread.sleep(35);
                                    } catch (InterruptedException ex) {
                                        ex.printStackTrace();
                                    }

                                    if (text.length() > 80) {
                                        this.parentFrame_vp.jLabelProgress.setText("      ");
                                        this.parentFrame_vp.jLabelProgress.setForeground(Color.WHITE);
                                    } else if (text.length() > 60) {
                                        this.parentFrame_vp.jLabelProgress.setForeground(Color.RED);
                                    } else if (text.length() > 30) {
                                        this.parentFrame_vp.jLabelProgress.setForeground(Color.ORANGE);

                                    }
                                }

                                if (status != 3) {
                                    this.parentFrame_vp.jLabelProgress.setText("      ");
                                }

                            });
                            tStatus.start();
//Send the email to supplier
                            roundButton6.setEnabled(false);
                            Thread tEmail = new Thread(() -> {

                                try {
                                    Thread.sleep(150);
                                } catch (InterruptedException ex) {
                                    ex.printStackTrace();
                                }

                                String time = parentFrame_vp.getTime_vp();
                                String date = parentFrame_vp.getDate_vp();
                                String orderId = String.valueOf(order_id);
                                String subject = "Feel Fresh - superMarket";

                                String items = "";

                                for (int i = 0; i < jTable1.getRowCount(); i++) {
                                    items += "    "
                                            + "            <tr>\n"
                                            + "                    <td class=\"td1\">" + jTable1.getValueAt(i, 1) + "</td>\n"
                                            + "                    <td class=\"td1\">" + jTable1.getValueAt(i, 2) + "</td>\n"
                                            + "                    <td class=\"td1\">" + jTable1.getValueAt(i, 3) + "</td>\n"
                                            + "                    <td class=\"td1 text-end\">" + jTable1.getValueAt(i, 4) + " " + jTable1.getValueAt(i, 5) + "</td>\n"
                                            + "            </tr>\n";
                                }

                                String body = "<!DOCTYPE html>\n"
                                        + "\n"
                                        + "<html>\n"
                                        + "\n"
                                        + "<head>\n"
                                        + "    <title>Email</title>\n"
                                        + "\n"
                                        + "    <style>\n"
                                        + "        * {\n"
                                        + "\n"
                                        + "            box-sizing: border-box;\n"
                                        + "\n"
                                        + "            color: gray;\n"
                                        + "\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .m0 {\n"
                                        + "            margin: 0;\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .p0 {\n"
                                        + "            padding: 0;\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .messageBox {\n"
                                        + "            border: 1px solid rgba(0, 0, 0, 0.212);\n"
                                        + "            padding: 10px;\n"
                                        + "            margin: 10px;\n"
                                        + "            border-radius: 20px;\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .infobox {\n"
                                        + "\n"
                                        + "            padding: 10px;\n"
                                        + "            margin: 10px;\n"
                                        + "\n"
                                        + "\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .text-center {\n"
                                        + "\n"
                                        + "            text-align: center;\n"
                                        + "\n"
                                        + "        }\n"
                                        + "        .text-end {\n"
                                        + "\n"
                                        + "            text-align: end;\n"
                                        + "\n"
                                        + "        }\n"
                                        + "\n"
                                        + "\n"
                                        + "        .text-color1 {\n"
                                        + "\n"
                                        + "            color: rgb(138, 153, 51);\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .table1 {\n"
                                        + "            width: 100%;\n"
                                        + "            margin-inline: 10px;\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .th1 {\n"
                                        + "            padding: 10px ;\n"
                                        + "            border-block: 1px solid rgba(0, 0, 0, 0.212);\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .td1 {\n"
                                        + "            padding-block: 5px;\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .align-center {\n"
                                        + "\n"
                                        + "            display: flex;\n"
                                        + "            justify-content: center;\n"
                                        + "\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .text-end {\n"
                                        + "            text-align: end;\n"
                                        + "        }\n"
                                        + "\n"
                                        + "\n"
                                        + "        .bottomBox {\n"
                                        + "            background-color: rgba(28, 9, 58, 0.589);\n"
                                        + "            padding: 10px;\n"
                                        + "            margin: 10px;\n"
                                        + "\n"
                                        + "            position: relative;\n"
                                        + "\n"
                                        + "        }\n"
                                        + "\n"
                                        + "        .text-color2 {\n"
                                        + "\n"
                                        + "            color: white;\n"
                                        + "            font-family: sans-serif;\n"
                                        + "            font-size: x-small;\n"
                                        + "            letter-spacing: 1px;\n"
                                        + "            font-weight: 10;\n"
                                        + "        }\n"
                                        + "    </style>\n"
                                        + "</head>\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "<body>\n"
                                        //Body                                    
                                        + "    <div>\n"
                                        + "\n"
                                        + "        <!-- Title -->\n"
                                        + "\n"
                                        + "        <div class=\"infobox\">\n"
                                        + "            <div class=\"text-center\">\n"
                                        + "                <img src=\"https://drive.google.com/thumbnail?id=1zfltuCYc9xptfApSAPjwj4NFT8npApgM\" width=\"150\">\n"
                                        + "            </div>\n"
                                        + "            <h1 class=\"text-center text-color1\">Order - Feel Fresh - " + orderId + "</h1>\n"
                                        + "\n"
                                        + "            <h6 style=\"margin-bottom: 0px;\">Date : " + date + "</h6>\n"
                                        + "            <h6 style=\"margin-block: 4px;\">Time : " + time + "</h6>\n"
                                        + "        </div>\n"
                                        + "\n"
                                        + "\n"
                                        + "        <!-- Message -->\n"
                                        + "        <div class=\"messageBox\">\n"
                                        + "            <h3>Message</h3>\n"
                                        + "            <p>" + jTextArea1.getText() + "</p>\n"
                                        + "\n"
                                        + "        </div>\n"
                                        + "\n"
                                        + "        <!-- LIst of items -->\n"
                                        + "        <h4 style=\"margin-left: 20px; margin-bottom: 10px;\">Items</h4>\n"
                                        + "        <div class=\"align-center\">\n"
                                        + "            <table class=\"table1\">\n"
                                        + "\n"
                                        + "\n"
                                        + "                <tr>\n"
                                        + "                    <th class=\"th1\">Product</th>\n"
                                        + "                    <th class=\"th1\">Brand</th>\n"
                                        + "                    <th class=\"th1\">Category</th>\n"
                                        + "                    <th class=\"th1\">Quantity</th>\n"
                                        + "                </tr>\n"
                                        + "\n"
                                        + items
                                        + "\n"
                                        + "            </table>\n"
                                        + "\n"
                                        + "\n"
                                        + "        </div>\n"
                                        + "        <h4 style=\"margin-right: 20px; text-align: end;\">Required Date : " + jDateChooser1.getDate() + "</h4>\n"
                                        + "\n"
                                        + "        <!-- Bottom -->\n"
                                        + "        <div class=\"bottomBox\">\n"
                                        + "            <!-- <p class=\"p0 m0 text-color2\" >\n"
                                        + "                <span style=\"position: absolute; left: 10px; bottom: 5px;\" class=\"text-color2\">Feel fresh &copy; All\n"
                                        + "                    rights received</span>\n"
                                        + "                <img style=\"position: absolute; left: 50%; transform: translateX(-50%); bottom: 5px;\"\n"
                                        + "                    src=\"https://drive.google.com/thumbnail?id=1zfltuCYc9xptfApSAPjwj4NFT8npApgM\" width=\"50\">\n"
                                        + "                <a style=\"position: absolute; right: 10px; bottom: 5px;\" href=\"#\"><span\n"
                                        + "                        class=\"text-color2\">feelfresh@gmail.com</span></a>\n"
                                        + "            </p> -->\n"
                                        + "\n"
                                        + "            <!-- <div style=\"position: absolute; width: 30%; height: 20px; top: 0; left: 0; text-align: center; \">\n"
                                        + "                \n"
                                        + "            </div>\n"
                                        + "            <div style=\"position: absolute; width: 40%; height: 20px; top: 0; left: 0; text-align: center; \">\n"
                                        + "                \n"
                                        + "            </div>\n"
                                        + "            <div style=\"position: absolute; width: 30%; height: 20px; top: 0; left: 0; text-align: center; \">\n"
                                        + "                <P class=\"m0 p0 text-color2\" style=\"text-align: end;\">feelfresh@gmail.com</P>\n"
                                        + "            </div> -->\n"
                                        + "\n"
                                        + "            <table width=\"100%\">\n"
                                        + "                <tr>\n"
                                        + "                    <td style=\"width: 40vh;\">\n"
                                        + "                        <P class=\"m0 p0 text-color2\" style=\"text-align: start;\">Feel Fresh &copy; All Rights Reserved\n"
                                        + "                        </P>\n"
                                        + "                    </td>\n"
                                        + "                    <td style=\"width: 20vh; text-align: center;\"><img \n"
                                        + "                            src=\"https://drive.google.com/thumbnail?id=1zfltuCYc9xptfApSAPjwj4NFT8npApgM\" width=\"50\" />\n"
                                        + "                    </td>\n"
                                        + "                    <td style=\"width: 40vh;\">\n"
                                        + "                        <P class=\"m0 p0 text-color2\" style=\"text-align: end;\">feelfresh@gmail.com</P>\n"
                                        + "                    </td>\n"
                                        + "                </tr>\n"
                                        + "            </table>\n"
                                        + "\n"
                                        + "        </div>\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "    </div>\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "    </div>\n"
                                        + "\n"
                                        + "\n"
                                        + "\n"
                                        + "</body>\n"
                                        + "\n"
                                        + "</html>";

                                Email email = new Email(this.parentFrame_vp);
                                email.setRecipients(emailLabel.getText());
                                email.setSubject(subject);
                                email.setBody(body);

                                status = email.sendEmail();

                                if (status == 0) {
                                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Email was sent successfully");
                                } else if (status == 1) {
                                    try {
                                        Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Email Sending Failed");
                                        MYSQL.executeIUD("UPDATE `order` SET `order`.`status` = 'Email_Failed' WHERE `order_id` = '"+orderId+"' ");
                                    } catch (Exception ex) {
                                        ex.printStackTrace();
                                    }

                                }

                                Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Go to the Order History to view the order.");
                                clearAll_vp();
                            });

                            tEmail.start();

//Send the email to supplier
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                //unable to insert
            }

        }


    }//GEN-LAST:event_roundButton6ActionPerformed

    private void roundButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton3ActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row that you want to remove", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            int row = jTable1.getSelectedRow();
            DefaultTableModel dtm = tableModelFull_vp;
            dtm.removeRow(row);
            jTable1.setModel(dtm);

            clearFilter_vp();

        }
    }//GEN-LAST:event_roundButton3ActionPerformed

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        clearFilter_vp();
        jTable1.setModel(tableModelFull_vp);
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        System.out.println(String.valueOf(jTable1.getRowCount()));

        addFilterSearch();

    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jTextFieldSearchProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchProductKeyPressed
        if (jTextFieldSearchProduct.getText().length() > 6
                && jTextFieldSearchProduct.getText().substring(0, 6).equals("Search")) {
            jTextFieldSearchProduct.setText("");
        }
    }//GEN-LAST:event_jTextFieldSearchProductKeyPressed

    private void jTextFieldSearchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchProductKeyReleased
        if (jTextFieldSearchProduct.getText().isBlank()) {
            jTextFieldSearchProduct.setText("Search Product");
        }

        addFilterSearch();

    }//GEN-LAST:event_jTextFieldSearchProductKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SelectSupplier_order selectSupplier = new SelectSupplier_order(this, true);
        selectSupplier.setLocationRelativeTo(this);
        selectSupplier.setVisible(true);

        loadOrderPending_vp();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jFormattedTextFieldQty.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jFormattedTextFieldQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldQtyKeyPressed
        if (jComboBoxUnit.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a unit ", "Error Message", JOptionPane.WARNING_MESSAGE);
            jComboBoxUnit.grabFocus();
        }
    }//GEN-LAST:event_jFormattedTextFieldQtyKeyPressed

    private void jComboBoxUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBoxBrand;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxUnit;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFieldQty;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAvaliable;
    private javax.swing.JLabel jLabelNoPending;
    private javax.swing.JLabel jLabelOrders;
    private javax.swing.JList<String> jListPendingOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelNoPendingOrders;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPanePendingOrder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldSearchProduct;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JLabel nameLabel;
    private desingcode.PanalRound panalRound1;
    private desingcode.PanalRound panalRound3;
    private desingcode.PanalRound panalRound4;
    private component.RoundButton roundButton1;
    private component.RoundButton roundButton3;
    private component.RoundButton roundButton5;
    private component.RoundButton roundButton6;
    private component.RoundButton roundButtonUpdateQTY;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the supplierID
     */
    public String getSupplierId() {
        return supplierId_vp;
    }

    /**
     * @param supplierId the supplierId_vp to set
     */
    public void setSupplierId(String supplierId) {
        this.supplierId_vp = supplierId;

        try {
            ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `supplier` "
                    + " INNER JOIN `supplier_mobile` ON `supplier`.`id` = `supplier_mobile`.`supplier_id` "
                    + " WHERE `id` = '" + supplierId + "'");
            if (resultSet.next()) {

                //Setting the user Details to the textfields in MakeOrder panel
                IdLabel.setText(resultSet.getString("id"));
                nameLabel.setText(resultSet.getString("first_name") + " " + resultSet.getString("last_name"));
                emailLabel.setText(resultSet.getString("email"));
                mobileLabel.setText(resultSet.getString("mobile"));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void loadOrderPending_vp() {

        DefaultListModel listModelPending = new DefaultListModel();
        Boolean pendingAvaliable = false;
        try {
            ResultSet rsOrderHis = MYSQL.executeSearch("SELECT * FROM `order` ");
            while (rsOrderHis.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(rsOrderHis.getString("id") + " " + rsOrderHis.getString("status") + " - " + new SimpleDateFormat("yyyy-MM-dd").format(rsOrderHis.getDate("created_at")));

                if (rsOrderHis.getString("status").equals("Pending")) {

                    pendingAvaliable = true;
                    listModelPending.addElement(vector);
                }
            }


            if (pendingAvaliable) {
                jListPendingOrder.setModel(listModelPending);
                jPanel6.removeAll();
                jPanel6.add(jScrollPanePendingOrder);

            } else {
                jPanel6.removeAll();
                jPanel6.add(jPanel5);
            }
            SwingUtilities.updateComponentTreeUI(this);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void loadCategories_vp() {
        try {
            ResultSet rsCat = MYSQL.executeSearch("SELECT * FROM `category`");
            DefaultComboBoxModel cbmodel = new DefaultComboBoxModel();
            cbmodel.addElement("Filter Category");
            while (rsCat.next()) {
                cbmodel.addElement(rsCat.getString("name"));
            }
            jComboBoxCategory.setModel(cbmodel);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void loadBrand() {
        DefaultComboBoxModel cbmodel = new DefaultComboBoxModel();
        cbmodel.addElement("Filter Brand");
        try {
            ResultSet rsBrand = MYSQL.executeSearch("SELECT * FROM `brand`");
            while (rsBrand.next()) {
                cbmodel.addElement(rsBrand.getString("name"));
            }

            jComboBoxBrand.setModel(cbmodel);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void clearFilter_vp() {
        jComboBoxBrand.setSelectedIndex(0);
        jComboBoxCategory.setSelectedIndex(0);
        jTextFieldSearchProduct.setText("Search Product");

        jTable1.setModel(tableModelFull_vp);
        tableFormatSRD_vp();

    }

    private void tableFormatSRD_vp() {

        /*
        formats the table by columnn->
                                width
                                resizible
                                drag&drop     
         */
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }
    }

    private void addFilterSearch() {
        jTable1.setModel(tableModelFull_vp);
        tableFormatSRD_vp();

        DefaultTableModel tableModelFiltered = new DefaultTableModel();
        tableModelFiltered.addColumn("id");
        tableModelFiltered.addColumn("Product Name");
        tableModelFiltered.addColumn("Brand");
        tableModelFiltered.addColumn("Category");
        tableModelFiltered.addColumn("QTY");
        tableModelFiltered.addColumn("Unit");

        Boolean category = false;
        Boolean brand = false;
        Boolean product = false;

        //checking if filters are avaliable
        if (jComboBoxCategory.getSelectedIndex() > 0) {
            category = true;
        }
        if (jComboBoxBrand.getSelectedIndex() > 0) {
            brand = true;
        }
        if (!jTextFieldSearchProduct.getText().isBlank()) {
            if (jTextFieldSearchProduct.getText().length() >= 6 && jTextFieldSearchProduct.getText().substring(0, 6).equals("Search")) {
            } else {
                product = true;
            }
        }
        //checking if filters are avaliable

        if (tableModelFull_vp.getRowCount() > 0) {

            for (int i = 0; i < tableModelFull_vp.getRowCount(); i++) {//iterating the full table

                if (product && category && brand) {
                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())
                            && jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())
                            && jTextFieldSearchProduct.getText().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()))) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (product && brand) {

                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())
                            && jTextFieldSearchProduct.getText().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()))) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }

                } else if (product && category) {
                    if (jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())
                            && jTextFieldSearchProduct.getText().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()))) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (product) {

                    if (jTextFieldSearchProduct.getText().length() <= (String.valueOf(jTable1.getValueAt(i, 1))).length()
                            && jTextFieldSearchProduct.getText().toLowerCase().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()).toLowerCase())) {
                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (brand && category) {

                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())
                            && jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }

                } else if (brand) {
                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())) {//if a brand is selected
                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (category) {
                    if (jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())) {//if a category is selected
                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);
                    }
                }

            }
        }

        if (brand || category || product) {
            jTable1.setModel(tableModelFiltered);
        }

        tableFormatSRD_vp();
    }

    HashMap<String, String> unitMap_vp = new HashMap<>();

    private void loadUnits_vp() {

        try {
            ResultSet rs = MYSQL.executeSearch("SELECT * FROM `unit` ");
            jComboBoxUnit.removeAllItems();
            jComboBoxUnit.addItem("Select Unit");
            while (rs.next()) {

                jComboBoxUnit.addItem(rs.getString("name"));
                unitMap_vp.put(rs.getString("name"), rs.getString("id"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void clearAll_vp() {
        nameLabel.setText("Name :");
        emailLabel.setText("Email : ");
        mobileLabel.setText("Mobile : ");

        jPanel6.removeAll();
        jPanel6.add(jPanel5);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        jTable1.setModel(dtm);
        jTextArea1.setText("");
        jFormattedTextFieldQty.setText("");

        clearFilter_vp();

        jDateChooser1.setDate(null);

        status = 3;//email status
        roundButton6.setEnabled(true);

    }
}
