/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel.order;

import gui.dialog.SelectProduct;
import gui.dialog.SelectSupplier_order;

import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.MYSQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.HashMap;

/**
 *
 * @author lgpavithra
 */
public class MakeOrder extends javax.swing.JPanel {

    private String supplierId_vp;
    private String[] productDetails_vp;
    DefaultTableModel tableModelFull_vp;//table model without filters

    /**
     * @param productDetails the productDetails_vp to set
     */
    public void setProductDetails(String[] productDetails) {

        // [0] id, [1] product name, [2] brand, [3] category, [4] qty , [5] unit
        clearFilter_vp();

        this.productDetails_vp = productDetails;

        if (jTable1.getRowCount() > 0) {
            Boolean foundColumn = false;
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                if (jTable1.getValueAt(i, 0).equals(productDetails[0])) {//if a row is avaliable

                    foundColumn = true;
                    //update quantity  

                    int option = JOptionPane.showConfirmDialog(this, "This item already exists. "
                            + "Do you want to update the quantity (This will add this quantity to existing quantity)", "Information", JOptionPane.INFORMATION_MESSAGE);

                    if (option == 0) {
                        jTable1.setValueAt(String.valueOf(Double.valueOf(productDetails[4]) + Double.valueOf((String) jTable1.getValueAt(i, 4))), i, 4);
                    }

                }
            }

            if (!foundColumn) {//it is no any row to match
                //set to table 
                Vector<String> vector = new Vector();
                vector.add(productDetails[0]);
                vector.add(productDetails[1]);
                vector.add(productDetails[2]);
                vector.add(productDetails[3]);
                vector.add(productDetails[4]);
                vector.add(productDetails[5]);

                DefaultTableModel dtm = tableModelFull_vp;
                dtm.addRow(vector);
            }

        } else {//row count is zero
            //set to table 
            Vector<String> vector = new Vector();
            vector.add(productDetails[0]);
            vector.add(productDetails[1]);
            vector.add(productDetails[2]);
            vector.add(productDetails[3]);
            vector.add(productDetails[4]);
            vector.add(productDetails[5]);

            DefaultTableModel dtm = tableModelFull_vp;
            dtm.addRow(vector);
        }

        SwingUtilities.updateComponentTreeUI(this);

    }

    /**
     * Creates new form NewJPanel
     */
    public MakeOrder() {
        initComponents();
        tableModelFull_vp = (DefaultTableModel) jTable1.getModel();

        loadCategories_vp();
        loadBrand();
        loadUnits_vp();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePendingOrder = new javax.swing.JScrollPane();
        jListPendingOrder = new javax.swing.JList<>();
        IdLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListOrderHistory = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanelNoPendingOrders = new javax.swing.JPanel();
        jLabelNoPending = new javax.swing.JLabel();
        jLabelOrders = new javax.swing.JLabel();
        jLabelAvaliable = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jComboBoxBrand = new javax.swing.JComboBox<>();
        jTextFieldSearchProduct = new javax.swing.JTextField();
        panalRound3 = new desingcode.PanalRound();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        roundButton3 = new component.RoundButton();
        roundButton6 = new component.RoundButton();
        roundButton5 = new component.RoundButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldQty = new javax.swing.JFormattedTextField();
        roundButtonUpdateQTY = new component.RoundButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxUnit = new javax.swing.JComboBox<>();
        roundButton1 = new component.RoundButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panalRound4 = new desingcode.PanalRound();
        jLabel5 = new javax.swing.JLabel();

        jListPendingOrder.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jListPendingOrder.setForeground(new java.awt.Color(255, 165, 76));
        jListPendingOrder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPendingOrder.setFixedCellHeight(30);
        jScrollPanePendingOrder.setViewportView(jListPendingOrder);

        IdLabel.setText("ID");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        nameLabel.setText("Name :");

        emailLabel.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        emailLabel.setText("e-Mail :");

        mobileLabel.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        mobileLabel.setText("Mobile :");

        jPanel2.setLayout(new java.awt.BorderLayout());

        jListOrderHistory.setFixedCellHeight(30);
        jScrollPane4.setViewportView(jListOrderHistory);

        jPanel2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jLabel11.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel11.setText("Order History");

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanelNoPendingOrders.setBackground(new java.awt.Color(252, 251, 236));
        jPanelNoPendingOrders.setLayout(new java.awt.GridLayout(3, 0));

        jLabelNoPending.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabelNoPending.setForeground(new java.awt.Color(255, 165, 76));
        jLabelNoPending.setText("  No Pending");
        jPanelNoPendingOrders.add(jLabelNoPending);

        jLabelOrders.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabelOrders.setForeground(new java.awt.Color(255, 165, 76));
        jLabelOrders.setText("  Orders");
        jPanelNoPendingOrders.add(jLabelOrders);

        jLabelAvaliable.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabelAvaliable.setForeground(new java.awt.Color(255, 165, 76));
        jLabelAvaliable.setText("  Avaliable");
        jPanelNoPendingOrders.add(jLabelAvaliable);

        jPanel6.add(jPanelNoPendingOrders, java.awt.BorderLayout.CENTER);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Select a Supplier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(mobileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxCategory.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jComboBoxCategory.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Category", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jComboBoxBrand.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jComboBoxBrand.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Brand", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBrandActionPerformed(evt);
            }
        });

        jTextFieldSearchProduct.setText("Search added products");
        jTextFieldSearchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchProductKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchProductKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jComboBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jTextFieldSearchProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panalRound3.setBackground(new java.awt.Color(209, 238, 184));
        panalRound3.setRoundTopLeft(40);

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("Message Body");

        javax.swing.GroupLayout panalRound3Layout = new javax.swing.GroupLayout(panalRound3);
        panalRound3.setLayout(panalRound3Layout);
        panalRound3Layout.setHorizontalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalRound3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panalRound3Layout.setVerticalGroup(
            panalRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        roundButton3.setForeground(new java.awt.Color(255, 51, 51));
        roundButton3.setText("Remove");
        roundButton3.setBorderColorHex("#E70101");
        roundButton3.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton3ActionPerformed(evt);
            }
        });

        roundButton6.setBackground(new java.awt.Color(233, 235, 235));
        roundButton6.setForeground(new java.awt.Color(0, 204, 153));
        roundButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/dashboard/inventory/place order/icons8-send-48.png"))); // NOI18N
        roundButton6.setText("Place Order");
        roundButton6.setBorderColorHex("#009900");
        roundButton6.setBorderWidth("0");
        roundButton6.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton6ActionPerformed(evt);
            }
        });

        roundButton5.setBackground(new java.awt.Color(0, 204, 153));
        roundButton5.setForeground(new java.awt.Color(255, 255, 255));
        roundButton5.setText("Add");
        roundButton5.setBorderColorHex("#009900");
        roundButton5.setBorderWidth("0");
        roundButton5.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton5ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quantity");

        jFormattedTextFieldQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00.00"))));
        jFormattedTextFieldQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jFormattedTextFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldQtyKeyPressed(evt);
            }
        });

        roundButtonUpdateQTY.setBackground(new java.awt.Color(0, 204, 153));
        roundButtonUpdateQTY.setForeground(new java.awt.Color(255, 255, 255));
        roundButtonUpdateQTY.setText("Update Qty");
        roundButtonUpdateQTY.setBorderColorHex("#009900");
        roundButtonUpdateQTY.setBorderWidth("0");
        roundButtonUpdateQTY.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButtonUpdateQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButtonUpdateQTYActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Required Date");

        jComboBoxUnit.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jComboBoxUnit.setForeground(new java.awt.Color(0, 153, 0));
        jComboBoxUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter Brand", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundButtonUpdateQTY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jFormattedTextFieldQty)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jComboBoxUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundButtonUpdateQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundButton1.setForeground(new java.awt.Color(102, 102, 102));
        roundButton1.setText("Clear Filters");
        roundButton1.setArc(20);
        roundButton1.setBorderColorHex("#666666");
        roundButton1.setBorderWidth("01");
        roundButton1.setFont(new java.awt.Font("Quicksand SemiBold", 0, 14)); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Category", "Brand", "QTY", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        panalRound4.setBackground(new java.awt.Color(209, 238, 184));
        panalRound4.setRoundTopLeft(50);

        jLabel5.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Make Order");

        javax.swing.GroupLayout panalRound4Layout = new javax.swing.GroupLayout(panalRound4);
        panalRound4.setLayout(panalRound4Layout);
        panalRound4Layout.setHorizontalGroup(
            panalRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panalRound4Layout.setVerticalGroup(
            panalRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(panalRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roundButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roundButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roundButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panalRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(panalRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(19, 19, 19)
                                .addComponent(panalRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(roundButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBrandActionPerformed

        addFilterSearch();

    }//GEN-LAST:event_jComboBoxBrandActionPerformed

    private void roundButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton5ActionPerformed

        SelectProduct selectProduct = new SelectProduct(this, true);
        selectProduct.setLocationRelativeTo(this);
        selectProduct.setVisible(true);

    }//GEN-LAST:event_roundButton5ActionPerformed

    private void roundButtonUpdateQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButtonUpdateQTYActionPerformed
        int row = jTable1.getSelectedRow();
        if (JOptionPane.showConfirmDialog(this, "Do you want to update qty of " + jTable1.getValueAt(row, 1) + "", "Information", JOptionPane.INFORMATION_MESSAGE) == 0) {
            jTable1.setValueAt(jFormattedTextFieldQty.getText(), row, 4);
        }


    }//GEN-LAST:event_roundButtonUpdateQTYActionPerformed

    private void roundButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton6ActionPerformed
        if (IdLabel.getText().equals("ID")) {//it was not selected a supplier
            JOptionPane.showMessageDialog(this, "Please select a supplier", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jTable1.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "There are no product has added", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a required date ", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jTextArea1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Message Body is empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            String supplierId = null;

            try {
                ResultSet rsSupplier = MYSQL.executeSearch("SELECT * FROM `supplier` WHERE `id` = '" + IdLabel.getText() + "' ");
                if (rsSupplier.next()) {
                    supplierId = rsSupplier.getString("id");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            if (supplierId != null) {
                try {
                    PreparedStatement preStatement = MYSQL.connection.prepareStatement("INSERT INTO `order` (`supplier_id`,`status`,`required_date`,`message`,`user_employee_nic`)"
                            + " VALUES ('" + supplierId + "','Pending',"//default set as pending
                            + " '" + new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate()) + "',"
                            + " '" + jTextArea1.getText() + "',"
                            + "  '199944557848' )  ", Statement.RETURN_GENERATED_KEYS);//Here User id has inserted manually **********************
                    //Toast message is better for this -T

                    preStatement.executeUpdate();
                    ResultSet rsKeys = preStatement.getGeneratedKeys();

                    if (rsKeys.next()) {

                        long order_id = rsKeys.getLong(1);

                        String q = "";//columns to insert
                        for (int i = 0; i < tableModelFull_vp.getRowCount(); i++) {
                            String product_id = String.valueOf(tableModelFull_vp.getValueAt(i, 0));
                            String qty = String.valueOf(tableModelFull_vp.getValueAt(i, 4));
                            String unit = unitMap_vp.get(tableModelFull_vp.getValueAt(i, 5));

                            if (q.isBlank()) {
                                q = "('" + order_id + "' , '" + product_id + "' , '" + qty + "' , '" + unit + "')";
                            } else {
                                q += ", ('" + order_id + "' , '" + product_id + "' , '" + qty + "' , '" + unit + "')";
                            }
                        }

                        try {

                            MYSQL.executeIUD("INSERT INTO `order_item` (`order_id`,`product_id`,`qty`,`unit_id`) VALUES "
                                    + q + " ");

                            JOptionPane.showMessageDialog(this, "Order is saved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                //unable to insert
            }

        }


    }//GEN-LAST:event_roundButton6ActionPerformed

    private void roundButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton3ActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row that you want to remove", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            int row = jTable1.getSelectedRow();
            DefaultTableModel dtm = tableModelFull_vp;
            dtm.removeRow(row);
            jTable1.setModel(dtm);

            clearFilter_vp();

        }
    }//GEN-LAST:event_roundButton3ActionPerformed

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        clearFilter_vp();
        jTable1.setModel(tableModelFull_vp);
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        System.out.println(String.valueOf(jTable1.getRowCount()));

        addFilterSearch();

    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jTextFieldSearchProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchProductKeyPressed
        if (jTextFieldSearchProduct.getText().length() > 6
                && jTextFieldSearchProduct.getText().substring(0, 6).equals("Search")) {
            jTextFieldSearchProduct.setText("");
        }
    }//GEN-LAST:event_jTextFieldSearchProductKeyPressed

    private void jTextFieldSearchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchProductKeyReleased
        if (jTextFieldSearchProduct.getText().isBlank()) {
            jTextFieldSearchProduct.setText("Search Product");
        }

        addFilterSearch();

    }//GEN-LAST:event_jTextFieldSearchProductKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SelectSupplier_order selectSupplier = new SelectSupplier_order(this, true);
        selectSupplier.setLocationRelativeTo(this);
        selectSupplier.setVisible(true);

        loadOrderHistory_vp();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jFormattedTextFieldQty.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBoxUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnitActionPerformed

    private void jFormattedTextFieldQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldQtyKeyPressed
        if (jComboBoxUnit.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a unit ", "Error Message", JOptionPane.WARNING_MESSAGE);
            jComboBoxUnit.grabFocus();
        }
    }//GEN-LAST:event_jFormattedTextFieldQtyKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBoxBrand;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxUnit;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFieldQty;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAvaliable;
    private javax.swing.JLabel jLabelNoPending;
    private javax.swing.JLabel jLabelOrders;
    private javax.swing.JList<String> jListOrderHistory;
    private javax.swing.JList<String> jListPendingOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelNoPendingOrders;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPanePendingOrder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldSearchProduct;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JLabel nameLabel;
    private desingcode.PanalRound panalRound3;
    private desingcode.PanalRound panalRound4;
    private component.RoundButton roundButton1;
    private component.RoundButton roundButton3;
    private component.RoundButton roundButton5;
    private component.RoundButton roundButton6;
    private component.RoundButton roundButtonUpdateQTY;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the supplierID
     */
    public String getSupplierId() {
        return supplierId_vp;
    }

    /**
     * @param supplierId the supplierId_vp to set
     */
    public void setSupplierId(String supplierId) {
        this.supplierId_vp = supplierId;

        try {
            ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `supplier` "
                    + " INNER JOIN `supplier_mobile` ON `supplier`.`id` = `supplier_mobile`.`supplier_id` "
                    + " WHERE `id` = '" + supplierId + "'");
            if (resultSet.next()) {

                //Setting the user Details to the textfields in MakeOrder panel
                IdLabel.setText(resultSet.getString("id"));
                nameLabel.setText(resultSet.getString("first_name") + " " + resultSet.getString("last_name"));
                emailLabel.setText(resultSet.getString("email"));
                mobileLabel.setText(resultSet.getString("mobiler"));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void loadOrderHistory_vp() {

        DefaultListModel listModelHistory = new DefaultListModel();
        DefaultListModel listModelPending = new DefaultListModel();
        Boolean pendingAvaliable = false;
        try {
            ResultSet rsOrderHis = MYSQL.executeSearch("SELECT * FROM `order` ");
            while (rsOrderHis.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(rsOrderHis.getString("id") + " " + rsOrderHis.getString("status") + " - " + new SimpleDateFormat("yyyy-MM-dd").format(rsOrderHis.getDate("created_at")));
                listModelHistory.addElement(vector);

                if (rsOrderHis.getString("status").equals("Pending")) {

                    pendingAvaliable = true;
                    listModelPending.addElement(vector);
                }
            }

            jListOrderHistory.setModel(listModelHistory);

            if (pendingAvaliable) {
                jListPendingOrder.setModel(listModelPending);
                jPanel6.removeAll();
                jPanel6.add(jScrollPanePendingOrder);

            } else {
                jPanel6.removeAll();
                jPanel6.add(jPanelNoPendingOrders);
            }
            SwingUtilities.updateComponentTreeUI(this);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void loadCategories_vp() {
        try {
            ResultSet rsCat = MYSQL.executeSearch("SELECT * FROM `category`");
            DefaultComboBoxModel cbmodel = new DefaultComboBoxModel();
            cbmodel.addElement("Filter Category");
            while (rsCat.next()) {
                cbmodel.addElement(rsCat.getString("name"));
            }
            jComboBoxCategory.setModel(cbmodel);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void loadBrand() {
        DefaultComboBoxModel cbmodel = new DefaultComboBoxModel();
        cbmodel.addElement("Filter Brand");
        try {
            ResultSet rsBrand = MYSQL.executeSearch("SELECT * FROM `brand`");
            while (rsBrand.next()) {
                cbmodel.addElement(rsBrand.getString("name"));
            }

            jComboBoxBrand.setModel(cbmodel);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void clearFilter_vp() {
        jComboBoxBrand.setSelectedIndex(0);
        jComboBoxCategory.setSelectedIndex(0);
        jTextFieldSearchProduct.setText("Search Product");

        jTable1.setModel(tableModelFull_vp);
        tableFormatSRD_vp();

    }

    private void tableFormatSRD_vp() {

        /*
        formats the table by columnn->
                                width
                                resizible
                                drag&drop     
         */
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }
    }

    private void addFilterSearch() {
        jTable1.setModel(tableModelFull_vp);
        tableFormatSRD_vp();

        DefaultTableModel tableModelFiltered = new DefaultTableModel();
        tableModelFiltered.addColumn("id");
        tableModelFiltered.addColumn("Product Name");
        tableModelFiltered.addColumn("Brand");
        tableModelFiltered.addColumn("Category");
        tableModelFiltered.addColumn("QTY");
        tableModelFiltered.addColumn("Unit");

        Boolean category = false;
        Boolean brand = false;
        Boolean product = false;

        //checking if filters are avaliable
        if (jComboBoxCategory.getSelectedIndex() > 0) {
            category = true;
        }
        if (jComboBoxBrand.getSelectedIndex() > 0) {
            brand = true;
        }
        if (!jTextFieldSearchProduct.getText().isBlank()) {
            if (jTextFieldSearchProduct.getText().length() >= 6 && jTextFieldSearchProduct.getText().substring(0, 6).equals("Search")) {
            } else {
                product = true;
            }
        }
        //checking if filters are avaliable

        if (tableModelFull_vp.getRowCount() > 0) {

            for (int i = 0; i < tableModelFull_vp.getRowCount(); i++) {//iterating the full table

                if (product && category && brand) {
                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())
                            && jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())
                            && jTextFieldSearchProduct.getText().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()))) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (product && brand) {

                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())
                            && jTextFieldSearchProduct.getText().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()))) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }

                } else if (product && category) {
                    if (jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())
                            && jTextFieldSearchProduct.getText().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()))) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (product) {

                    if (jTextFieldSearchProduct.getText().length() <= (String.valueOf(jTable1.getValueAt(i, 1))).length()
                            && jTextFieldSearchProduct.getText().toLowerCase().equals(String.valueOf(jTable1.getValueAt(i, 1)).substring(0, jTextFieldSearchProduct.getText().length()).toLowerCase())) {
                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (brand && category) {

                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())
                            && jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())) {

                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }

                } else if (brand) {
                    if (jTable1.getValueAt(i, 2).equals(jComboBoxBrand.getSelectedItem())) {//if a brand is selected
                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);

                    }
                } else if (category) {
                    if (jTable1.getValueAt(i, 3).equals(jComboBoxCategory.getSelectedItem())) {//if a category is selected
                        //add filterd rows
                        Vector<String> v = new Vector<>();
                        v.add((String) jTable1.getValueAt(i, 0));
                        v.add((String) jTable1.getValueAt(i, 1));
                        v.add((String) jTable1.getValueAt(i, 2));
                        v.add((String) jTable1.getValueAt(i, 3));
                        v.add((String) jTable1.getValueAt(i, 4));

                        tableModelFiltered.addRow(v);
                    }
                }

            }
        }

        if (brand || category || product) {
            jTable1.setModel(tableModelFiltered);
        }

        tableFormatSRD_vp();
    }

    HashMap<String, String> unitMap_vp = new HashMap<>();

    private void loadUnits_vp() {

        try {
            ResultSet rs = MYSQL.executeSearch("SELECT * FROM `unit` ");
            jComboBoxUnit.removeAllItems();
            jComboBoxUnit.addItem("Select Unit");
            while (rs.next()) {

                jComboBoxUnit.addItem(rs.getString("name"));
                unitMap_vp.put(rs.getString("name"), rs.getString("id"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
