/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel.supplierRegistration;


import java.awt.BorderLayout;


import javax.swing.JOptionPane;
import model.MYSQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.HashMap;
import java.util.Vector;
import javax.swing.SwingUtilities;

import java.util.Vector;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Supplier extends javax.swing.JPanel {

    private final SupplierUpdate supplierUpdate_ni;

    public Supplier() {
        initComponents();
        loadSupplier_ni();

        supplierUpdate_ni = new SupplierUpdate(this);
    }

    private void loadSupplier_ni() {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        loadSupplier_ni();
    }
    
     private void loadSupplier_ni() {


        try {

            ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `supplier`");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {

                Vector<String> vector = new Vector<>();


                vector.add(resultSet.getString("id"));

                vector.add(resultSet.getString("first_name"));
                vector.add(resultSet.getString("last_name"));
                vector.add(resultSet.getString("email"));
                vector.add(resultSet.getString("no"));
                vector.add(resultSet.getString("line1"));
                vector.add(resultSet.getString("line2"));

                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();


        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        uJTextfield6 = new component.UJTextfield();
        uJTextfield4 = new component.UJTextfield();
        uJTextfield2 = new component.UJTextfield();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uJTextfield5 = new component.UJTextfield();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uJTextfield1 = new component.UJTextfield();
        uJTextfield3 = new component.UJTextfield();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);


        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);

            }
        });

        uJTextfield6.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        uJTextfield4.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        uJTextfield2.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel3.setText("Last Name");

        jLabel5.setText("Address No");

        jLabel7.setText("Address Line 2");

        uJTextfield5.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel6.setText("Address Line 1");

        jLabel4.setText("Email");

        jLabel2.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel2.setText("First Name");

        uJTextfield1.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        uJTextfield3.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Supplier Registration");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

                "ID", "First Name", "Last Name", "Email", "Address No", "Address Line 1", "Address Line 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false

                "First Name", "Last Name", "Email", "Address No", "Address Line 1", "Address Line 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false

            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jScrollPane1.setViewportView(jTable1);


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()

                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)

                .addComponent(jScrollPane1)

                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()

                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jButton2.setText("Clear All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, java.awt.BorderLayout.LINE_END);

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);


                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))

            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(uJTextfield5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(uJTextfield3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(uJTextfield1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uJTextfield4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uJTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                            .addComponent(uJTextfield6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())

                            .addComponent(uJTextfield6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uJTextfield1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uJTextfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJTextfield6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJTextfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)

                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
//Create Account
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String firstName_ni = uJTextfield1.getText();
        String larstName_ni = uJTextfield2.getText();
        String email_ni = uJTextfield3.getText();
        String addressNo_ni = uJTextfield4.getText();
        String addressLine1_ni = uJTextfield5.getText();
        String addressLine2_ni = uJTextfield6.getText();
        String registerDate_ni = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        if (firstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter First Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (larstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Last Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (email_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please  Enter Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (!email_ni.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (addressNo_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address No.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine1_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 1.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine2_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 2.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
//data chek
                ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `supplier` WHERE`email` = '" + email_ni + "'");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "Supplier Allredy Register ", "WARNING", JOptionPane.WARNING_MESSAGE);

                } else {
                    //data inserte
                    MYSQL.executeIUD("INSERT INTO `supplier` (`first_name`,`last_name`,`email`,`reg_date`,`no`,`line1`,`line2`)VALUES('" + firstName_ni + "','" + larstName_ni + "','" + email_ni + "','" + registerDate_ni + "','" + addressNo_ni + "','" + addressLine1_ni + "','" + addressLine2_ni + "')");
                    JOptionPane.showMessageDialog(this, "Supplier Account Create Success", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);


                    reset_ni();

                    reset();

                    loadSupplier_ni();

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed
//button reset 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        reset_ni();
    }//GEN-LAST:event_jButton2ActionPerformed
//update customer details text filde add
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() >= 2) {
            jPanel3.removeAll();
            jPanel3.add(supplierUpdate_ni);
            SwingUtilities.updateComponentTreeUI(jPanel3);

            int row = jTable1.getSelectedRow();

            String firstName_ni = String.valueOf(jTable1.getValueAt(row, 1));
            uJTextfield1.setText(firstName_ni);

            String larstName_ni = String.valueOf(jTable1.getValueAt(row, 2));
            uJTextfield2.setText(larstName_ni);

            String email_ni = String.valueOf(jTable1.getValueAt(row, 3));
            uJTextfield3.setText(email_ni);

            String addressNo_ni = String.valueOf(jTable1.getValueAt(row, 4));
            uJTextfield4.setText(addressNo_ni);

            String addressLine1_ni = String.valueOf(jTable1.getValueAt(row, 5));
            uJTextfield5.setText(addressLine1_ni);

            String addressLine2_ni = String.valueOf(jTable1.getValueAt(row, 6));
            uJTextfield6.setText(addressLine2_ni);

        } else {
            setDefault_ni();
        }


    }//GEN-LAST:event_jTable1MouseClicked


    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       setDefault_ni();
    }//GEN-LAST:event_jPanel1MouseClicked
//updatesupplier 

    void updateSupplier_ni() {
        int row = jTable1.getSelectedRow();
        
        String firstName_ni = uJTextfield1.getText();
        String larstName_ni = uJTextfield2.getText();
        String email_ni = uJTextfield3.getText();
        String addressNo_ni = uJTextfield4.getText();
        String addressLine1_ni = uJTextfield5.getText();
        String addressLine2_ni = uJTextfield6.getText();
        String id_ni = String.valueOf(jTable1.getValueAt(row, 0));
        
        if (firstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter First Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (larstName_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Last Name.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (email_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please  Enter Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (!email_ni.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email.", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else if (addressNo_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address No.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine1_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 1.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (addressLine2_ni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Address Line 2.", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                //data chek
                ResultSet resultSet = MYSQL.executeSearch("SELECT * FROM `supplier` WHERE`first_name`= '"+firstName_ni+"' and `last_name` = '"+larstName_ni+"' and`email` = '" + email_ni + "'and`no` = '"+addressNo_ni+"'and `line1` = '"+addressLine1_ni+"' and `line2` = '"+addressLine2_ni+"'");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "Supplier details allready register ", "WARNING", JOptionPane.WARNING_MESSAGE);

                } else {
                    //data update
                    MYSQL.executeIUD("UPDATE`supplier` SET`first_name`= '" + firstName_ni + "',`last_name`= '" + larstName_ni + "',`email`= '" + email_ni + "',`no`= '" + addressNo_ni + "',`line1` = '" + addressLine1_ni + "',`line2` = '" + addressLine2_ni + "' WHERE `id` = '"+id_ni+"'");
                    JOptionPane.showMessageDialog(this, "Supplier Account Update Success", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

                    reset_ni();
                    loadSupplier_ni();

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }
    //reset clear button
    void supplierUpdateReset_ni(){
    reset_ni();
    }

    //set customer crate account button mouseclick one and border click 
    private void setDefault_ni() {
        jPanel3.removeAll();
        jPanel3.add(jButton1, BorderLayout.CENTER);
        jPanel3.add(jButton2, BorderLayout.EAST);
        SwingUtilities.updateComponentTreeUI(jPanel3);
        reset_ni();

    }

       reset();
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    component.UJTextfield uJTextfield1;
    component.UJTextfield uJTextfield2;
    component.UJTextfield uJTextfield3;
    component.UJTextfield uJTextfield4;
    component.UJTextfield uJTextfield5;
    component.UJTextfield uJTextfield6;
    // End of variables declaration//GEN-END:variables

    private void reset_ni() {

    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private component.UJTextfield uJTextfield1;
    private component.UJTextfield uJTextfield2;
    private component.UJTextfield uJTextfield3;
    private component.UJTextfield uJTextfield4;
    private component.UJTextfield uJTextfield5;
    private component.UJTextfield uJTextfield6;
    // End of variables declaration//GEN-END:variables

    private void reset() {


        uJTextfield1.grabFocus();
        uJTextfield1.setText("");
        uJTextfield2.setText("");
        uJTextfield3.setText("");
        uJTextfield4.setText("");
        uJTextfield5.setText("");
        uJTextfield6.setText("");

    }



}
