/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panel.inventory;

import inventory_process.inventory.InventoryManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GRNProduct;
import model.MYSQL;
import model.dto.DTOGenerator;
import model.dto.GrnDTO;
import model.dto.ProductDTO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author senad
 */
public class GRNTerminal extends javax.swing.JPanel {

    /**
     * Creates new form GRNTerminal
     */
    private ArrayList<GRNProduct> productList = new ArrayList<>(); // List to store product details
    private DefaultComboBoxModel<String> productComboBoxModel = new DefaultComboBoxModel<>(); // ComboBox model for autocomplete
    private DefaultComboBoxModel<String> orderComboBoxModel = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel<String> supplierComboBoxModel = new DefaultComboBoxModel<>();

    private boolean isProductComboBoxInteracted = false; // Track user interaction with the combo box

    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public GRNTerminal() {
        initComponents();

        // Populate combo box with product names from the database
        loadActiveProducts();
        // Populate combo boxes
        populateOrderComboBox();
        populateSupplierComboBox();

        // Add autocomplete functionality
        AutoCompleteDecorator.decorate(productComboBox);
        AutoCompleteDecorator.decorate(orderComboBox);
        AutoCompleteDecorator.decorate(supplierComboBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sellingPriceTxtField = new javax.swing.JTextField();
        qtyTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        totalSubTotalLabel = new javax.swing.JLabel();
        productComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exdDateChooser = new com.toedter.calendar.JDateChooser();
        buyingPriceTxtField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        discountTxtField = new javax.swing.JTextField();
        paidAmountTxtField = new javax.swing.JTextField();
        netTotalLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        orderIDValue = new javax.swing.JLabel();
        employeeNICLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        outstandingLabel = new javax.swing.JLabel();
        supplierComboBox = new javax.swing.JComboBox<>();
        discardButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        orderComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 102, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setFocusPainted(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Quantity");

        sellingPriceTxtField.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        sellingPriceTxtField.setForeground(new java.awt.Color(51, 51, 51));
        sellingPriceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingPriceTxtFieldActionPerformed(evt);
            }
        });

        qtyTxtField.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        qtyTxtField.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Buying Price");

        jLabel17.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Sub Total:");

        totalSubTotalLabel.setFont(new java.awt.Font("OCR-B 10 BT", 1, 50)); // NOI18N
        totalSubTotalLabel.setForeground(new java.awt.Color(0, 102, 102));
        totalSubTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSubTotalLabel.setText("00.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalSubTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalSubTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        productComboBox.setEditable(true);
        productComboBox.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        productComboBox.setForeground(new java.awt.Color(51, 51, 51));
        productComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        addButton.setText("Add");
        addButton.setFocusable(false);
        addButton.setRequestFocusEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Selling Price");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("EXD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Product");

        exdDateChooser.setForeground(new java.awt.Color(51, 51, 51));
        exdDateChooser.setFont(new java.awt.Font("Poppins", 0, 19)); // NOI18N

        buyingPriceTxtField.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        buyingPriceTxtField.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exdDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productComboBox, 0, 159, Short.MAX_VALUE)
                                    .addComponent(buyingPriceTxtField))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtyTxtField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sellingPriceTxtField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addGap(0, 66, Short.MAX_VALUE)))))
                        .addGap(28, 28, 28))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buyingPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellingPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Detaiils", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(244, 244, 244));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Paid to:");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Outstanding:");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Total:");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Net Total:");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Paid Amount:");

        totalLabel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        totalLabel.setText("00.00");

        discountTxtField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        discountTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTxtFieldActionPerformed(evt);
            }
        });
        discountTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountTxtFieldKeyReleased(evt);
            }
        });

        paidAmountTxtField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        paidAmountTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidAmountTxtFieldActionPerformed(evt);
            }
        });
        paidAmountTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidAmountTxtFieldKeyReleased(evt);
            }
        });

        netTotalLabel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        netTotalLabel.setText("00.00");

        jLabel24.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel24.setText("Paid by:");

        jLabel25.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("orderID:");

        orderIDValue.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        orderIDValue.setText("None");

        employeeNICLabel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        employeeNICLabel.setText("200327311404");

        jLabel29.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("discount:");

        outstandingLabel.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        outstandingLabel.setText("00.00");

        supplierComboBox.setEditable(true);
        supplierComboBox.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeNICLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIDValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paidAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outstandingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierComboBox, 0, 143, Short.MAX_VALUE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderIDValue))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeNICLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(totalLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(netTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outstandingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        discardButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        discardButton.setText("Discard");

        printButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        printButton.setText("Print GRN");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Payment Details", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        orderComboBox.setFont(new java.awt.Font("Poppins", 0, 19)); // NOI18N
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002" }));
        orderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel7.setText("Order ID");

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 23)); // NOI18N
        jLabel3.setText("GRN No: 223");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jLabel21.setText("PO table");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "product", "qty", "rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel22.setText("POID - 001");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(27, 27, 27))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jLabel30.setText("Remove");

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pname", "Qty", "Buying Price", "Selling Price", "subtotal", "EXD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(0).setMinWidth(0);
            itemTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            itemTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel23.setText("Item Table");

        jLabel20.setText("edit");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(10, 10, 10)))
                .addGap(30, 30, 30))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        if (supplierComboBox.getSelectedIndex() != 0) {
            //supplier_name
            String supplierName = String.valueOf(supplierComboBox.getSelectedItem()).trim();
            //supplier_name
            String supplierID = supplierMap.get(supplierName);
            //user_employee_nic
            String empNic = employeeNICLabel.getText();
            //order_id
            String orderID = orderIDValue.getText();
            //total_amount
            String total = totalLabel.getText();
            //discount_amount
            String discount = discountTxtField.getText();
            //paid_amount
            String paidAmt = paidAmountTxtField.getText();
            //outstanding_amount
            String outStandingAmt = outstandingLabel.getText();

            //DTO
            DefaultTableModel dtm = (DefaultTableModel) itemTable.getModel();
            if (dtm.getRowCount() > 0) {

                ArrayList<ProductDTO> productList = new ArrayList<>();
                for (int i = 0; i < dtm.getRowCount(); i++) {
//                    System.out.println(dtm.getValueAt(i, 0));
                    ProductDTO productDto = DTOGenerator.getInstance().generateProductDTO(String.valueOf(itemTable.getValueAt(i, 0)),
                            Double.parseDouble(String.valueOf(itemTable.getValueAt(i, 3))),
                            Double.parseDouble(String.valueOf(itemTable.getValueAt(i, 4))),
                            Integer.parseInt(String.valueOf(itemTable.getValueAt(i, 2))),
                            String.valueOf(itemTable.getValueAt(i, 6)));

                    productList.add(productDto);

                }
                GrnDTO grnDto = DTOGenerator.getInstance().generateGrnDTO(productList,
                        1,
                        Double.parseDouble(total),
                        Double.parseDouble(discount),
                        Double.parseDouble(paidAmt),
                        Double.parseDouble(outStandingAmt),
                        Integer.parseInt(supplierID));
                
                InventoryManager.getInstance().addStocks(grnDto);
                
            } else {
                JOptionPane.showMessageDialog(this, "Please add products", "Warning", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Please Select a supplier", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            // Validate product selection before proceeding
            if (!validateProductSelection()) {
                return; // Stop if validation fails
            }

            // Get selected product from the combo box
            String product_name = (String) productComboBox.getSelectedItem();
            String qtyStr = qtyTxtField.getText().trim();
            String buyingPriceStr = buyingPriceTxtField.getText().trim();
            String sellingPriceStr = sellingPriceTxtField.getText().trim();

            // Validate product name
            if (product_name == null || product_name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a product from the list.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validate numeric fields
            if (qtyStr.isEmpty() || buyingPriceStr.isEmpty() || sellingPriceStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Quantity, buying price, and selling price fields cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int qty;
            double buying_price;
            double selling_price;

            try {
                qty = Integer.parseInt(qtyStr);
                buying_price = Double.parseDouble(buyingPriceStr);
                selling_price = Double.parseDouble(sellingPriceStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Please enter valid numeric values for quantity, buying price, and selling price.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Check for positive values
            if (qty <= 0 || buying_price <= 0 || selling_price <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity, buying price, and selling price must be positive values.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validate that selling price is greater than buying price
            if (selling_price <= buying_price) {
                JOptionPane.showMessageDialog(this, "The selling price must be greater than the buying price.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Calculate subtotal
            double subtotal = qty * buying_price;

            // Create a new product object
            GRNProduct product = new GRNProduct(product_name, qty, buying_price, selling_price, subtotal);

            // Get the DefaultTableModel for the JTable
            DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
            boolean itemExists = false;

            // Loop through the table to check if the product already exists
            for (int row = 0; row < model.getRowCount(); row++) {
                String existingProductName = (String) model.getValueAt(row, 0); // Column 0: Product Name
                if (existingProductName.equals(product_name)) {
                    // If the product already exists, update the quantity and subtotal
                    int existingQty = (int) model.getValueAt(row, 1); // Column 1: Quantity
                    double existingSubtotal = (double) model.getValueAt(row, 3); // Column 3: Subtotal

                    // Update the quantity and subtotal
                    int newQty = existingQty + qty;
                    double newSubtotal = newQty * buying_price;
                    model.setValueAt(newQty, row, 1); // Update Quantity
                    model.setValueAt(newSubtotal, row, 3); // Update Subtotal

                    // Exit the loop after updating the item
                    itemExists = true;
                    break;
                }
            }

            // If the product doesn't exist, add a new row to the table
            if (!itemExists) {
                model.addRow(new Object[]{
                    productMap.get(product.getProductName()),
                    product.getProductName(),
                    product.getQuantity(),
                    product.getBuyingPrice(),
                    product.getSellingPrice(),
                    product.getSubtotal(),
                    sdf.format(exdDateChooser.getDate())
                });
            }

            // Clear input fields after adding
            productComboBox.setSelectedIndex(0);
            qtyTxtField.setText("");
            buyingPriceTxtField.setText("");
            sellingPriceTxtField.setText("");

            // Set focus to the productComboBox
            productComboBox.grabFocus();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        // After adding the item, call the method to update the totals
        updateTotalLabels();
    }//GEN-LAST:event_addButtonActionPerformed

    private void sellingPriceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingPriceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingPriceTxtFieldActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // Mark that the combo box has been interacted with
        isProductComboBoxInteracted = true;
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void orderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderComboBoxActionPerformed
        try {
            // Get the selected order ID
            String selectedOrder = (String) orderComboBox.getSelectedItem();

            // Validate selection
            if (selectedOrder != null && !selectedOrder.trim().isEmpty() && !selectedOrder.equals("None")) {
                // Set the order ID label
                orderIDValue.setText(selectedOrder);

                // Convert selectedOrder to integer
                int orderId = Integer.parseInt(selectedOrder.trim());

                // Query to get the supplier ID for the selected order
                String query = "SELECT supplier_id FROM `order` WHERE id = " + orderId;
                ResultSet rs = MYSQL.executeSearch(query);

                if (rs.next()) {
                    int supplierId = rs.getInt("supplier_id");

                    // Query to get the full name of the supplier
                    String supplierQuery = "SELECT CONCAT(first_name, ' ', last_name) AS full_name FROM `supplier` WHERE id = " + supplierId;
                    ResultSet supplierRs = MYSQL.executeSearch(supplierQuery);

                    if (supplierRs.next()) {
                        String supplierName = supplierRs.getString("full_name");

                        // Set the corresponding supplier in the supplierComboBox
                        supplierComboBox.setSelectedItem(supplierName);
                    } else {
                        JOptionPane.showMessageDialog(this, "Supplier not found for the selected order.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Order not found in the database.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Handle invalid selection
                JOptionPane.showMessageDialog(this, "Please select a valid order ID.", "Validation Error", JOptionPane.WARNING_MESSAGE);

                // Clear fields to reset state
                orderIDValue.setText("None");
                supplierComboBox.setSelectedIndex(0);

                // Exit early to prevent additional processing
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid order ID format: " + ex.getMessage(), "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An error occurred while selecting supplier: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orderComboBoxActionPerformed

    private void discountTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTxtFieldActionPerformed
//        try {
//            // Get the value from the totalLabel
//            double total = Double.parseDouble(totalLabel.getText().trim());
//
//            // Get the discount value entered by the user
//            String discountStr = discountTxtField.getText().trim();
//            double discount = 0.0;
//
//            // Validate if the discount field is not empty and is a valid number
//            if (!discountStr.isEmpty()) {
//                discount = Double.parseDouble(discountStr);
//
//                // Check if discount is not greater than the total
//                if (discount > total) {
//                    JOptionPane.showMessageDialog(this, "Discount cannot be greater than the total.", "Validation Error", JOptionPane.WARNING_MESSAGE);
//                    return;
//                }
//            }
//
//            // Calculate the net total (total - discount)
//            double netTotal = total - discount;
//
//            // Update the netTotalLabel with the calculated net total
//            netTotalLabel.setText(String.format("%.2f", netTotal));
//            outstandingLabel.setText(String.format("%.2f", netTotal));
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Please enter a valid number for the discount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_discountTxtFieldActionPerformed

    private void paidAmountTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidAmountTxtFieldActionPerformed
        try {
            // Get the values from the netTotalLabel and paidAmountTxtField
            double netTotal = Double.parseDouble(netTotalLabel.getText().trim()); // Get the net total from the label
            String paidAmountStr = paidAmountTxtField.getText().trim();

            if (paidAmountStr.isEmpty()) {
                // If no value is entered, set the outstanding to the net total
                outstandingLabel.setText(String.format("%.2f", netTotal));
            } else {
                double paidAmount = Double.parseDouble(paidAmountStr);

                // Validate if the paid amount exceeds the net total
                if (paidAmount > netTotal) {
                    // Show error message if paid amount exceeds net total
                    JOptionPane.showMessageDialog(this, "Paid amount cannot exceed the net total.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                    // Optionally clear the paid amount field or set it to a valid value
                    paidAmountTxtField.setText("");
                    outstandingLabel.setText(String.format("%.2f", netTotal)); // Reset outstanding label to the net total
                    return;
                }

                // Calculate outstanding amount
                double outstandingAmount = netTotal - paidAmount;

                // Update the outstandingLabel with the calculated outstanding amount
                outstandingLabel.setText(String.format("%.2f", outstandingAmount));
            }
        } catch (NumberFormatException ex) {
            // Handle invalid input for numeric fields
            JOptionPane.showMessageDialog(this, "Please enter a valid number for the paid amount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_paidAmountTxtFieldActionPerformed

    private void discountTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountTxtFieldKeyReleased
        try {
            // Get the value from the totalLabel
            double total = Double.parseDouble(totalLabel.getText().trim());

            // Get the discount value entered by the user
            String discountStr = discountTxtField.getText().trim();
            double discount = 0.0;

            // Validate if the discount field is not empty
            if (!discountStr.isEmpty()) {
                // Check if the entered value is numeric
                if (!discountStr.matches("\\d+(\\.\\d+)?")) { // Allow integers or decimals
                    JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for the discount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                    discountTxtField.setText(""); // Clear the invalid input
                    netTotalLabel.setText(String.format("%.2f", total)); // Reset net total
                    return;
                }

                // Parse the discount value
                discount = Double.parseDouble(discountStr);

                // Check if discount is greater than the total
                if (discount > total) {
                    JOptionPane.showMessageDialog(this, "Discount cannot be greater than the total amount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                    discountTxtField.setText(""); // Clear the invalid input
                    netTotalLabel.setText(String.format("%.2f", total)); // Reset net total
                    return;
                }
            }

            // Calculate the net total (total - discount)
            double netTotal = total - discount;

            // Update the netTotalLabel with the calculated net total
            netTotalLabel.setText(String.format("%.2f", netTotal));

        } catch (NumberFormatException ex) {
            // Handle invalid numeric values (though this should be rare with prior validation)
            JOptionPane.showMessageDialog(this, "An unexpected error occurred while processing the discount value.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_discountTxtFieldKeyReleased

    private void paidAmountTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountTxtFieldKeyReleased
        try {
            // Get the value from netTotalLabel
            double netTotal = Double.parseDouble(netTotalLabel.getText().trim()); // Net total from the label
            String paidAmountStr = paidAmountTxtField.getText().trim(); // Value entered in the paidAmountTxtField

            if (paidAmountStr.isEmpty()) {
                // If no value is entered, set the outstanding amount to the net total
                outstandingLabel.setText(String.format("%.2f", netTotal));
                return;
            }

            // Attempt to parse the paid amount
            double paidAmount = Double.parseDouble(paidAmountStr);

            // Validate that the paid amount is not negative or greater than the net total
            if (paidAmount < 0) {
                JOptionPane.showMessageDialog(this, "Paid amount cannot be negative.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                paidAmountTxtField.setText(""); // Clear the input field
                outstandingLabel.setText(String.format("%.2f", netTotal)); // Reset outstanding label
                return;
            }

            if (paidAmount > netTotal) {
                JOptionPane.showMessageDialog(this, "Paid amount cannot exceed the net total.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                paidAmountTxtField.setText(""); // Clear the input field
                outstandingLabel.setText(String.format("%.2f", netTotal)); // Reset outstanding label
                return;
            }

            // Calculate the outstanding amount
            double outstandingAmount = netTotal - paidAmount;

            // Update the outstandingLabel with the calculated amount
            outstandingLabel.setText(String.format("%.2f", outstandingAmount));

        } catch (NumberFormatException ex) {
            // Handle invalid numeric input
            JOptionPane.showMessageDialog(this, "Please enter a valid number for the paid amount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            paidAmountTxtField.setText(""); // Clear invalid input
            outstandingLabel.setText(String.format("%.2f", Double.parseDouble(netTotalLabel.getText().trim()))); // Reset outstanding label
        }
    }//GEN-LAST:event_paidAmountTxtFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField buyingPriceTxtField;
    private javax.swing.JButton discardButton;
    private javax.swing.JTextField discountTxtField;
    private javax.swing.JLabel employeeNICLabel;
    private com.toedter.calendar.JDateChooser exdDateChooser;
    private javax.swing.JTable itemTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel netTotalLabel;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JLabel orderIDValue;
    private javax.swing.JLabel outstandingLabel;
    private javax.swing.JTextField paidAmountTxtField;
    private javax.swing.JButton printButton;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JTextField qtyTxtField;
    private javax.swing.JTextField sellingPriceTxtField;
    private javax.swing.JComboBox<String> supplierComboBox;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalSubTotalLabel;
    // End of variables declaration//GEN-END:variables
HashMap<String, String> productMap = new HashMap<>();

    private void loadActiveProducts() {
        try {
            // Clear the combo box model to avoid duplicates
            productComboBoxModel.removeAllElements();

            // Add default 'Select' option
            productComboBoxModel.addElement("Select");

            // Query to fetch active products
            String query = "SELECT * FROM product WHERE status = 'Active'";
            ResultSet rs = MYSQL.executeSearch(query);

            // Populate the combo box model with product names
            while (rs.next()) {
                String productName = rs.getString("name");
                productMap.put(productName, rs.getString("id"));
                productComboBoxModel.addElement(productName);
            }

            // Set the model to the combo box
            productComboBox.setModel(productComboBoxModel);

            // Set the default selected item to 'Select'
            productComboBox.setSelectedIndex(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading product list: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validateProductSelection() {
        if (!isProductComboBoxInteracted) {
            // User has not interacted yet; do not validate
            return true;
        }

        // Get the selected item
        String selectedProduct = (String) productComboBox.getSelectedItem();

        // Check if the selected item is null or 'Select'
        if (selectedProduct == null || selectedProduct.equals("Select")) {
            JOptionPane.showMessageDialog(this,
                    "Please select a valid product name from the list.",
                    "Invalid Selection",
                    JOptionPane.WARNING_MESSAGE);

            // Reset focus to the productComboBox
            productComboBox.requestFocus();
            return false;
        }

        // Check if the selected item is not in the combo box model
        boolean isProductValid = false;
        for (int i = 0; i < productComboBoxModel.getSize(); i++) {
            if (productComboBoxModel.getElementAt(i).equals(selectedProduct)) {
                isProductValid = true;
                break;
            }
        }

        if (!isProductValid) {
            JOptionPane.showMessageDialog(this,
                    "The entered product name is not valid. Please select a product name from the list.",
                    "Invalid Product Name",
                    JOptionPane.WARNING_MESSAGE);

            // Reset focus to the productComboBox
            productComboBox.requestFocus();
            return false;
        }

        return true; // Validation passed
    }

    private void populateOrderComboBox() {
        try {
            String orderQuery = "SELECT id FROM `order` WHERE `status` = 'Pending'";
            ResultSet orderResults = MYSQL.executeSearch(orderQuery);

            orderComboBoxModel.addElement("None"); // Add a "None" option as the first item
            while (orderResults.next()) {
                int orderId = orderResults.getInt("id");
                orderComboBoxModel.addElement(String.valueOf(orderId)); // Convert order ID to String and add
            }
            orderComboBox.setModel(orderComboBoxModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load order IDs: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    HashMap<String, String> supplierMap = new HashMap<>();

    private void populateSupplierComboBox() {
        try {
            String supplierQuery = "SELECT CONCAT(first_name, ' ', last_name) AS full_name, id FROM `supplier` WHERE `status` = 'Active'";
            ResultSet supplierResults = MYSQL.executeSearch(supplierQuery);

            supplierComboBoxModel.addElement("Select"); // Add a "Select" option as the first item
            while (supplierResults.next()) {
                supplierMap.put(supplierResults.getString("full_name"), supplierResults.getString("id"));
                String supplierName = supplierResults.getString("full_name");
                supplierComboBoxModel.addElement(supplierName); // Add supplier name to the combo box model
            }
            supplierComboBox.setModel(supplierComboBoxModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to load supplier names: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateTotalLabels() {
        // Get the table model
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();

        // Check if there are no items in the table
        if (model.getRowCount() == 0) {
            // Set both labels to 0.00 if there are no items
            totalSubTotalLabel.setText("0.00");
            totalLabel.setText("0.00");
            netTotalLabel.setText("0.00");
            return;
        }

        double totalSubTotal = 0.0;
        double total = 0.0;

        // Loop through all rows in the table and sum the subtotal values
        for (int row = 0; row < model.getRowCount(); row++) {
            // Get the value from the "Subtotal" column (assuming it's the 4th column)
            Object subtotalObj = model.getValueAt(row, 5); // Column index for Subtotal (adjust if necessary)

            // Check if the value is numeric and add it to the total
            if (subtotalObj instanceof Number) {
                totalSubTotal += ((Number) subtotalObj).doubleValue();
            }
        }

        // Set the calculated subtotals to the respective labels
        totalSubTotalLabel.setText(String.format("%.2f", totalSubTotal));

        // Assuming total is calculated from the subtotal (or any other business rule you have)
        total = totalSubTotal; // or apply any additional logic for total if required

        // Set the total to the totalLabel
        totalLabel.setText(String.format("%.2f", total));

        // Set the total to the netTotalLabel
        netTotalLabel.setText(String.format("%.2f", total));

        // Set the total to the netTotalLabel
        outstandingLabel.setText(String.format("%.2f", total));
    }
}
